--<ScriptOptions statementTerminator=";"/>

CONNECT TO ADMSEGDS;

CREATE SCHEMA "ADMSEGDS" AUTHORIZATION "SYSIBM";

CREATE SEQUENCE "ADMSEGDS"."CUST_SEQ" AS INTEGER  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER;

CREATE SEQUENCE "ADMSEGDS"."GPXUSR_SEQ" AS INTEGER  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER;

CREATE SEQUENCE "ADMSEGDS"."SEGGRUPO_SEQ" AS INTEGER  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER;

CREATE SEQUENCE "ADMSEGDS"."SIST_SEQ" AS INTEGER  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER;

CREATE TABLE "ADMSEGDS"."ADVISE_INDEX" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL DEFAULT '', 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL DEFAULT '', 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL DEFAULT '', 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL DEFAULT '', 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL DEFAULT '', 
		"STMTNO" INTEGER NOT NULL DEFAULT 0, 
		"SECTNO" INTEGER NOT NULL DEFAULT 0, 
		"QUERYNO" INTEGER NOT NULL DEFAULT 0, 
		"QUERYTAG" CHAR(20) NOT NULL DEFAULT '', 
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL DEFAULT '', 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL DEFAULT '', 
		"COLNAMES" CLOB(2097152) INLINE LENGTH 164 NOT NULL, 
		"UNIQUERULE" CHAR(1) NOT NULL DEFAULT '', 
		"COLCOUNT" SMALLINT NOT NULL DEFAULT 0, 
		"IID" SMALLINT NOT NULL DEFAULT 0, 
		"NLEAF" INTEGER NOT NULL DEFAULT 0, 
		"NLEVELS" SMALLINT NOT NULL DEFAULT 0, 
		"FIRSTKEYCARD" BIGINT NOT NULL DEFAULT 0, 
		"FULLKEYCARD" BIGINT NOT NULL DEFAULT 0, 
		"CLUSTERRATIO" SMALLINT NOT NULL DEFAULT 0, 
		"CLUSTERFACTOR" DOUBLE NOT NULL DEFAULT 0, 
		"USERDEFINED" SMALLINT NOT NULL DEFAULT 0, 
		"SYSTEM_REQUIRED" SMALLINT NOT NULL DEFAULT 0, 
		"CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"STATS_TIME" TIMESTAMP DEFAULT CURRENT TIMESTAMP, 
		"PAGE_FETCH_PAIRS" VARCHAR(254) NOT NULL DEFAULT '', 
		"REMARKS" VARCHAR(254) DEFAULT '', 
		"DEFINER" VARCHAR(128) NOT NULL DEFAULT '', 
		"CONVERTED" CHAR(1) NOT NULL DEFAULT '', 
		"SEQUENTIAL_PAGES" INTEGER NOT NULL DEFAULT 0, 
		"DENSITY" INTEGER NOT NULL DEFAULT 0, 
		"FIRST2KEYCARD" BIGINT NOT NULL DEFAULT 0, 
		"FIRST3KEYCARD" BIGINT NOT NULL DEFAULT 0, 
		"FIRST4KEYCARD" BIGINT NOT NULL DEFAULT 0, 
		"PCTFREE" SMALLINT NOT NULL DEFAULT -1, 
		"UNIQUE_COLCOUNT" SMALLINT NOT NULL DEFAULT -1, 
		"MINPCTUSED" SMALLINT NOT NULL DEFAULT 0, 
		"REVERSE_SCANS" CHAR(1) NOT NULL DEFAULT 'N', 
		"USE_INDEX" CHAR(1), 
		"CREATION_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"PACKED_DESC" BLOB(1048576) INLINE LENGTH 164 NOT LOGGED, 
		"RUN_ID" TIMESTAMP, 
		"INDEXTYPE" VARCHAR(4) NOT NULL DEFAULT '', 
		"EXISTS" CHAR(1) NOT NULL DEFAULT 'N', 
		"RIDTOBLOCK" CHAR(1) NOT NULL DEFAULT 'N'
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."ADVISE_INSTANCE" (
		"START_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"END_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"MODE" VARCHAR(4) NOT NULL DEFAULT '', 
		"WKLD_COMPRESSION" CHAR(4) NOT NULL DEFAULT 'NONE', 
		"STATUS" CHAR(9) NOT NULL DEFAULT ''
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."ADVISE_MQT" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL DEFAULT '', 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL DEFAULT '', 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL DEFAULT '', 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL DEFAULT '', 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL DEFAULT '', 
		"STMTNO" INTEGER NOT NULL DEFAULT 0, 
		"SECTNO" INTEGER NOT NULL DEFAULT 0, 
		"NAME" VARCHAR(128) NOT NULL, 
		"CREATOR" VARCHAR(128) NOT NULL DEFAULT '', 
		"IID" SMALLINT NOT NULL DEFAULT 0, 
		"CREATE_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"STATS_TIME" TIMESTAMP DEFAULT CURRENT TIMESTAMP, 
		"NUMROWS" DOUBLE NOT NULL DEFAULT 0, 
		"NUMCOLS" SMALLINT NOT NULL DEFAULT 0, 
		"ROWSIZE" DOUBLE NOT NULL DEFAULT 0, 
		"BENEFIT" DOUBLE NOT NULL DEFAULT 0.0, 
		"USE_MQT" CHAR(1), 
		"MQT_SOURCE" CHAR(1), 
		"QUERY_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"CREATION_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"SAMPLE_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"COLSTATS" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"EXTRA_INFO" BLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT "SYSIBM"."BLOB"('') NOT LOGGED, 
		"TBSPACE" VARCHAR(128) NOT NULL DEFAULT '', 
		"RUN_ID" TIMESTAMP, 
		"REFRESH_TYPE" CHAR(1) NOT NULL DEFAULT '', 
		"EXISTS" CHAR(1) NOT NULL DEFAULT 'N'
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."ADVISE_PARTITION" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL DEFAULT '', 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL DEFAULT '', 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL DEFAULT '', 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL DEFAULT '', 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL DEFAULT '', 
		"STMTNO" INTEGER NOT NULL DEFAULT 0, 
		"SECTNO" INTEGER NOT NULL DEFAULT 0, 
		"QUERYNO" INTEGER NOT NULL DEFAULT 0, 
		"QUERYTAG" CHAR(20) NOT NULL DEFAULT '', 
		"TBNAME" VARCHAR(128) NOT NULL, 
		"TBCREATOR" VARCHAR(128) NOT NULL DEFAULT '', 
		"PMID" SMALLINT NOT NULL, 
		"TBSPACE" VARCHAR(128) NOT NULL DEFAULT '', 
		"COLNAMES" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"COLCOUNT" SMALLINT NOT NULL DEFAULT 0, 
		"REPLICATE" CHAR(1) NOT NULL DEFAULT 'N', 
		"COST" DOUBLE NOT NULL, 
		"USEIT" CHAR(1), 
		"RUN_ID" TIMESTAMP
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."ADVISE_TABLE" (
		"RUN_ID" TIMESTAMP, 
		"TABLE_NAME" VARCHAR(128) NOT NULL, 
		"TABLE_SCHEMA" VARCHAR(128) NOT NULL DEFAULT '', 
		"TABLESPACE" VARCHAR(128) NOT NULL DEFAULT '', 
		"SELECTION_FLAG" VARCHAR(8) NOT NULL DEFAULT '', 
		"TABLE_EXISTS" CHAR(1) NOT NULL DEFAULT '', 
		"USE_TABLE" CHAR(1) NOT NULL DEFAULT '', 
		"GEN_COLUMNS" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"ORGANIZE_BY" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"CREATION_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"ALTER_COMMAND" CLOB(2097152) INLINE LENGTH 164 NOT NULL DEFAULT '' NOT LOGGED, 
		"DISKUSE" DOUBLE NOT NULL DEFAULT 0
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."ADVISE_WORKLOAD" (
		"WORKLOAD_NAME" CHAR(128) NOT NULL DEFAULT 'WK0', 
		"STATEMENT_NO" INTEGER NOT NULL DEFAULT 1, 
		"STATEMENT_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL NOT LOGGED, 
		"STATEMENT_TAG" VARCHAR(256) NOT NULL DEFAULT '', 
		"FREQUENCY" INTEGER NOT NULL DEFAULT 1, 
		"IMPORTANCE" DOUBLE NOT NULL DEFAULT 1, 
		"WEIGHT" DOUBLE NOT NULL DEFAULT 1, 
		"COST_BEFORE" DOUBLE, 
		"COST_AFTER" DOUBLE, 
		"COMPILABLE" CHAR(17)
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."CATMODIFYBIT" (
		"ICVEMODIFYBIT" SMALLINT NOT NULL, 
		"CNOMBREMOD" VARCHAR(300) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_ARGUMENT" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"OPERATOR_ID" INTEGER NOT NULL, 
		"ARGUMENT_TYPE" CHAR(8) NOT NULL, 
		"ARGUMENT_VALUE" VARCHAR(1024), 
		"LONG_ARGUMENT_VALUE" CLOB(2097152) INLINE LENGTH 164 NOT LOGGED
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_DIAGNOSTIC" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"DIAGNOSTIC_ID" INTEGER NOT NULL, 
		"CODE" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_DIAGNOSTIC_DATA" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"DIAGNOSTIC_ID" INTEGER NOT NULL, 
		"ORDINAL" INTEGER NOT NULL, 
		"TOKEN" VARCHAR(1000), 
		"TOKEN_LONG" BLOB(3145728) INLINE LENGTH 164 NOT LOGGED
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_INSTANCE" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_OPTION" CHAR(1) NOT NULL, 
		"SNAPSHOT_TAKEN" CHAR(1) NOT NULL, 
		"DB2_VERSION" CHAR(7) NOT NULL, 
		"SQL_TYPE" CHAR(1) NOT NULL, 
		"QUERYOPT" INTEGER NOT NULL, 
		"BLOCK" CHAR(1) NOT NULL, 
		"ISOLATION" CHAR(2) NOT NULL, 
		"BUFFPAGE" INTEGER NOT NULL, 
		"AVG_APPLS" INTEGER NOT NULL, 
		"SORTHEAP" INTEGER NOT NULL, 
		"LOCKLIST" INTEGER NOT NULL, 
		"MAXLOCKS" SMALLINT NOT NULL, 
		"LOCKS_AVAIL" INTEGER NOT NULL, 
		"CPU_SPEED" DOUBLE NOT NULL, 
		"REMARKS" VARCHAR(254), 
		"DBHEAP" INTEGER NOT NULL, 
		"COMM_SPEED" DOUBLE NOT NULL, 
		"PARALLELISM" CHAR(2) NOT NULL, 
		"DATAJOINER" CHAR(1) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_OBJECT" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"OBJECT_SCHEMA" VARCHAR(128) NOT NULL, 
		"OBJECT_NAME" VARCHAR(128) NOT NULL, 
		"OBJECT_TYPE" CHAR(2) NOT NULL, 
		"CREATE_TIME" TIMESTAMP, 
		"STATISTICS_TIME" TIMESTAMP, 
		"COLUMN_COUNT" SMALLINT NOT NULL, 
		"ROW_COUNT" BIGINT NOT NULL, 
		"WIDTH" INTEGER NOT NULL, 
		"PAGES" INTEGER NOT NULL, 
		"DISTINCT" CHAR(1) NOT NULL, 
		"TABLESPACE_NAME" VARCHAR(128), 
		"OVERHEAD" DOUBLE NOT NULL, 
		"TRANSFER_RATE" DOUBLE NOT NULL, 
		"PREFETCHSIZE" INTEGER NOT NULL, 
		"EXTENTSIZE" INTEGER NOT NULL, 
		"CLUSTER" DOUBLE NOT NULL, 
		"NLEAF" INTEGER NOT NULL, 
		"NLEVELS" INTEGER NOT NULL, 
		"FULLKEYCARD" BIGINT NOT NULL, 
		"OVERFLOW" INTEGER NOT NULL, 
		"FIRSTKEYCARD" BIGINT NOT NULL, 
		"FIRST2KEYCARD" BIGINT NOT NULL, 
		"FIRST3KEYCARD" BIGINT NOT NULL, 
		"FIRST4KEYCARD" BIGINT NOT NULL, 
		"SEQUENTIAL_PAGES" INTEGER NOT NULL, 
		"DENSITY" INTEGER NOT NULL, 
		"STATS_SRC" CHAR(1) NOT NULL, 
		"AVERAGE_SEQUENCE_GAP" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_FETCH_GAP" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_SEQUENCE_FETCH_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_RANDOM_PAGES" DOUBLE NOT NULL, 
		"AVERAGE_RANDOM_FETCH_PAGES" DOUBLE NOT NULL, 
		"NUMRIDS" BIGINT NOT NULL, 
		"NUMRIDS_DELETED" BIGINT NOT NULL, 
		"NUM_EMPTY_LEAFS" BIGINT NOT NULL, 
		"ACTIVE_BLOCKS" BIGINT NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_OPERATOR" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"OPERATOR_ID" INTEGER NOT NULL, 
		"OPERATOR_TYPE" CHAR(6) NOT NULL, 
		"TOTAL_COST" DOUBLE NOT NULL, 
		"IO_COST" DOUBLE NOT NULL, 
		"CPU_COST" DOUBLE NOT NULL, 
		"FIRST_ROW_COST" DOUBLE NOT NULL, 
		"RE_TOTAL_COST" DOUBLE NOT NULL, 
		"RE_IO_COST" DOUBLE NOT NULL, 
		"RE_CPU_COST" DOUBLE NOT NULL, 
		"COMM_COST" DOUBLE NOT NULL, 
		"FIRST_COMM_COST" DOUBLE NOT NULL, 
		"BUFFERS" DOUBLE NOT NULL, 
		"REMOTE_TOTAL_COST" DOUBLE NOT NULL, 
		"REMOTE_COMM_COST" DOUBLE NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_PREDICATE" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"OPERATOR_ID" INTEGER NOT NULL, 
		"PREDICATE_ID" INTEGER NOT NULL, 
		"HOW_APPLIED" CHAR(5) NOT NULL, 
		"WHEN_EVALUATED" CHAR(3) NOT NULL, 
		"RELOP_TYPE" CHAR(2) NOT NULL, 
		"SUBQUERY" CHAR(1) NOT NULL, 
		"FILTER_FACTOR" DOUBLE NOT NULL, 
		"PREDICATE_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT LOGGED
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_STATEMENT" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"QUERYNO" INTEGER NOT NULL, 
		"QUERYTAG" CHAR(20) NOT NULL, 
		"STATEMENT_TYPE" CHAR(2) NOT NULL, 
		"UPDATABLE" CHAR(1) NOT NULL, 
		"DELETABLE" CHAR(1) NOT NULL, 
		"TOTAL_COST" DOUBLE NOT NULL, 
		"STATEMENT_TEXT" CLOB(2097152) INLINE LENGTH 164 NOT NULL NOT LOGGED, 
		"SNAPSHOT" BLOB(10485760) INLINE LENGTH 196 NOT LOGGED, 
		"QUERY_DEGREE" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."EXPLAIN_STREAM" (
		"EXPLAIN_REQUESTER" VARCHAR(128) NOT NULL, 
		"EXPLAIN_TIME" TIMESTAMP NOT NULL, 
		"SOURCE_NAME" VARCHAR(128) NOT NULL, 
		"SOURCE_SCHEMA" VARCHAR(128) NOT NULL, 
		"SOURCE_VERSION" VARCHAR(64) NOT NULL, 
		"EXPLAIN_LEVEL" CHAR(1) NOT NULL, 
		"STMTNO" INTEGER NOT NULL, 
		"SECTNO" INTEGER NOT NULL, 
		"STREAM_ID" INTEGER NOT NULL, 
		"SOURCE_TYPE" CHAR(1) NOT NULL, 
		"SOURCE_ID" INTEGER NOT NULL, 
		"TARGET_TYPE" CHAR(1) NOT NULL, 
		"TARGET_ID" INTEGER NOT NULL, 
		"OBJECT_SCHEMA" VARCHAR(128), 
		"OBJECT_NAME" VARCHAR(128), 
		"STREAM_COUNT" DOUBLE NOT NULL, 
		"COLUMN_COUNT" SMALLINT NOT NULL, 
		"PREDICATE_ID" INTEGER NOT NULL, 
		"COLUMN_NAMES" CLOB(2097152) INLINE LENGTH 164 NOT LOGGED, 
		"PMID" SMALLINT NOT NULL, 
		"SINGLE_NODE" CHAR(5), 
		"PARTITION_COLUMNS" CLOB(2097152) INLINE LENGTH 164 NOT LOGGED
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLCENTROSCT" (
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"CDSCCSCT" VARCHAR(20) NOT NULL, 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT NOT NULL, 
		"ICVEUSUDIRECTOR" BIGINT, 
		"ICVEOFICINACIS" INTEGER, 
		"CTITULAR" VARCHAR(255), 
		"ICVEUNIDADADMING" INTEGER
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLCENTROSSCT" (
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"ICVEPAIS" SMALLINT, 
		"ICVEENTIDADFED" SMALLINT, 
		"ICVEMUNICIPIO" SMALLINT, 
		"CDSCCENTROSCT" VARCHAR(25)
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLDEPARTAMENTO" (
		"ICVEDEPARTAMENTO" INTEGER NOT NULL, 
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"ICVEOFICINAINGRESOS" INTEGER, 
		"CDSCDEPARTAMENTO" VARCHAR(255), 
		"ICVEOFICINACIS" INTEGER, 
		"CPREFIJOLIC" VARCHAR(5), 
		"ICVEDEPTOLIC" SMALLINT, 
		"ICVEAREARECAUDADORA" INTEGER, 
		"ICVECSCTINGRESOS" BIGINT, 
		"ICVEOFICINAINGRESO" INTEGER
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLDEPARTAMENTO_LIC" (
		"ICVEDEPARTAMENTO" INTEGER NOT NULL, 
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"ICVEOFICINAINGRESO" INTEGER, 
		"CDSCDEPARTAMENTO" VARCHAR(255), 
		"ICVEOFICINACIS" INTEGER, 
		"CPREFIJOLIC" VARCHAR(5), 
		"ICVEDEPTOLIC" SMALLINT, 
		"LGENERADOCTOS" SMALLINT NOT NULL DEFAULT 0, 
		"CNOMFIRMADOCTO" VARCHAR(300), 
		"CPUESTOFIRMADOCTO" VARCHAR(300), 
		"CFIRMADOCTO" VARCHAR(60), 
		"CNOMFIRMAINGLES" VARCHAR(60), 
		"CPUESTOFIRMAINGLES" VARCHAR(300), 
		"ICVEUNIDADADMING" INTEGER DEFAULT 0, 
		"ICVECENTROSCTING" INTEGER DEFAULT 0, 
		"ICVEAREARECAUDING" INTEGER DEFAULT 0, 
		"LCIMPRESION" SMALLINT, 
		"CDEPTOSDET" VARCHAR(50), 
		"LINTERNET" SMALLINT
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS YES;

CREATE TABLE "ADMSEGDS"."GRLDEPENDENCIA" (
		"ICVEDEPENDENCIA" SMALLINT NOT NULL, 
		"CDSCDEPENDENCIA" VARCHAR(25)
	)
	DATA CAPTURE NONE 
	IN "SGRLDEPENDENCIA"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLENTIDADFED" (
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT NOT NULL, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CABREVIATURA" VARCHAR(30) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLENTIDADFED"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLMODULO" (
		"ICVEUNIMED" SMALLINT NOT NULL, 
		"ICVEMODULO" SMALLINT NOT NULL, 
		"CDSCMODULO" VARCHAR(100) NOT NULL, 
		"CCALLE" VARCHAR(50), 
		"CCOLONIA" VARCHAR(30), 
		"ICP" BIGINT NOT NULL, 
		"CCIUDAD" VARCHAR(50), 
		"ICVEPAIS" SMALLINT, 
		"ICVEESTADO" SMALLINT, 
		"ICVEMUNICIPIO" SMALLINT, 
		"CTEL" VARCHAR(20), 
		"CCORREOE" VARCHAR(100), 
		"LINTERCONSULTA" SMALLINT NOT NULL DEFAULT 0, 
		"LVIGENTE" SMALLINT NOT NULL, 
		"ICVEOFICINA" SMALLINT DEFAULT 1, 
		"CCLUES" VARCHAR(20), 
		"LVALIDA" SMALLINT DEFAULT 0
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS YES;

CREATE TABLE "ADMSEGDS"."GRLMUNICIPIO" (
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT NOT NULL, 
		"ICVEMUNICIPIO" BIGINT NOT NULL, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CABREVIATURA" VARCHAR(30) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLMUNICIPIO"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLPAIS" (
		"ICVEPAIS" SMALLINT NOT NULL, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CABREVIATURA" VARCHAR(30) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLPAIS"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLUNIMED" (
		"ICVEUNIMED" SMALLINT NOT NULL, 
		"CDSCUNIMED" VARCHAR(30), 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEESTADO" SMALLINT NOT NULL, 
		"ICVEMUNICIPIO" SMALLINT NOT NULL, 
		"LCIS" SMALLINT DEFAULT 0, 
		"LPAGO" SMALLINT NOT NULL DEFAULT 0, 
		"CCALLE" VARCHAR(50), 
		"CCOLONIA" VARCHAR(30), 
		"ICP" BIGINT, 
		"CCIUDAD" VARCHAR(50), 
		"CTEL" VARCHAR(20), 
		"CCORREOE" VARCHAR(100), 
		"LPRIVADA" SMALLINT, 
		"LVIGENTE" SMALLINT NOT NULL, 
		"ICVEUSURESPUM" INTEGER DEFAULT 0, 
		"ICVEUDDADMIVA" VARCHAR(30), 
		"LLABORATORIO" DECIMAL(1 , 0)
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS YES;

CREATE TABLE "ADMSEGDS"."GRLUSRXDEPTO" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEDEPARTAMENTO" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLUSRXDEPTO_LIC" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEDEPARTAMENTO" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."GRLUSRXMDOTRANS" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEMDOTRANS" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS YES;

CREATE TABLE "ADMSEGDS"."GRLUSUMEDICOS" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEUNIMED" INTEGER NOT NULL, 
		"ICVEPROCESO" INTEGER NOT NULL, 
		"ICVEMODULO" INTEGER NOT NULL, 
		"ICVESERVICIO" INTEGER NOT NULL, 
		"ICVERAMA" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PPEQUIPO" (
		"ICVEPERSONA" INTEGER NOT NULL, 
		"CEQUIPO" VARCHAR(100), 
		"CDSCEQUIPO" VARCHAR(75), 
		"CNS" VARCHAR(50), 
		"ICANTIDAD" INTEGER, 
		"ICVETIPOTRANS" INTEGER, 
		"CMARCA" VARCHAR(50), 
		"CSUBMARCA" VARCHAR(50), 
		"CCOLOR" VARCHAR(35), 
		"IMODELO" INTEGER, 
		"CPLACAS" VARCHAR(20), 
		"CNOTARJETA" VARCHAR(20), 
		"ICVEEQUIPO" INTEGER NOT NULL, 
		"CTIPOTRANS" VARCHAR(50), 
		"ICVEPERSONAVEH" INTEGER, 
		"CNOECONOMICO" VARCHAR(50), 
		"COBSERVACIONES" VARCHAR(100), 
		"CAREA" VARCHAR(100), 
		"CCODIGOID" VARCHAR(50), 
		"CMOTOR" VARCHAR(50), 
		"CSERIE" VARCHAR(50), 
		"CVERIFICACION" VARCHAR(50), 
		"CPOLIZASEGURO" VARCHAR(50), 
		"DTFECHAVENCSEGURO" DATE, 
		"CNVANOTARJETA" VARCHAR(50), 
		"DANTISITIO" DECIMAL(5 , 0), 
		"CDIASINGRESO" VARCHAR(150), 
		"ICVETIPOREGEQUIPO" INTEGER, 
		"ICVEASIGNADO" INTEGER
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PPUSRXPER" (
		"ICVEPERSONA" INTEGER NOT NULL, 
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"TSREGISTRO" TIMESTAMP NOT NULL, 
		"ICVEUSUREG" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PRYACTIVIDADES" (
		"ICVEPROYECTO" INTEGER NOT NULL, 
		"ICVEACTIVIDAD" INTEGER NOT NULL, 
		"ICVEESTRUCTURA" INTEGER NOT NULL, 
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVESTATUS" INTEGER NOT NULL, 
		"CDSCACTIVIDAD" VARCHAR(150) NOT NULL, 
		"CDSCDETALLE" VARCHAR(512), 
		"DTINICIO" DATE, 
		"DTFIN" DATE, 
		"TSINI" TIMESTAMP, 
		"TSFIN" TIMESTAMP, 
		"TSREGISTRO" TIMESTAMP, 
		"IPRIORIDAD" INTEGER, 
		"IPORCENTAJE" INTEGER
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PRYESTATUS" (
		"ICVEESTATUS" INTEGER NOT NULL, 
		"CDSCESTATUS" VARCHAR(50) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PRYESTRUCTURA" (
		"ICVEPROYECTO" INTEGER NOT NULL, 
		"ICVEESTRUCTURA" INTEGER NOT NULL, 
		"IORDEN" INTEGER NOT NULL, 
		"CDSCESTRUCTURA" VARCHAR(100) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PRYLOG" (
		"ICVEPROYECTO" INTEGER NOT NULL, 
		"ICVEACTIVIDAD" INTEGER NOT NULL, 
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"TSREGISTRO" TIMESTAMP NOT NULL, 
		"CNOTA" VARCHAR(256) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PRYPROYECTO" (
		"ICVEPROYECTO" INTEGER NOT NULL, 
		"CDSCPROYECTO" VARCHAR(100) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."PRYUSUARIO" (
		"ICVEPROYECTO" INTEGER NOT NULL, 
		"ICVEUSUARIO" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SECUENCIAS" (
		"TABLA" VARCHAR(50) NOT NULL, 
		"INDICE" BIGINT
	)
	DATA CAPTURE NONE 
	IN "SSECUENCIAS"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGBITMOD" (
		"ICVEBITMOD" BIGINT NOT NULL, 
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"TFECHAMOD" TIMESTAMP NOT NULL, 
		"ICVEMODIFYBIT" SMALLINT NOT NULL, 
		"ICVESISTEMA" SMALLINT, 
		"ICVEGRUPO" SMALLINT, 
		"ICVEPROGRAMA" SMALLINT, 
		"COBSERVACION" VARCHAR(500)
	)
	DATA CAPTURE NONE 
	IN "SGRLCENTROSSCT"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGGPOXUSR" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"ICVEGRUPO" SMALLINT NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SSEGGPOXUSR"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGGRUPO" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEGRUPO" SMALLINT NOT NULL, 
		"CDSCGRUPO" VARCHAR(30) NOT NULL, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0, 
		"LINTERNO" SMALLINT, 
		"LHORARIO" SMALLINT
	)
	DATA CAPTURE NONE 
	IN "SSEGGRUPO"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGMENU" (
		"IORDEN" BIGINT NOT NULL, 
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"CDSCMENU" VARCHAR(100), 
		"CREFERENCIA" VARCHAR(200), 
		"IOPCPADRE" BIGINT, 
		"LBLOQUEADO" SMALLINT DEFAULT 0, 
		"CNOMPAGINA" VARCHAR(100), 
		"CCLASECSS" VARCHAR(50)
	)
	DATA CAPTURE NONE 
	IN "SSEGMENU"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGPERMISOXGPO" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEGRUPO" SMALLINT NOT NULL, 
		"ICVEPROGRAMA" SMALLINT NOT NULL, 
		"LEJECUCION" SMALLINT NOT NULL DEFAULT 1, 
		"LACTUALIZACION" SMALLINT NOT NULL DEFAULT 1
	)
	DATA CAPTURE NONE 
	IN "SSEGPERMISOXGPO"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGPERMISOXUSR" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEPROGRAMA" SMALLINT NOT NULL, 
		"LEJECUCION" SMALLINT NOT NULL DEFAULT 1, 
		"LACTUALIZACION" SMALLINT NOT NULL DEFAULT 1
	)
	DATA CAPTURE NONE 
	IN "SSEGPERMISOXUSR"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGPROGRAMA" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEPROGRAMA" SMALLINT NOT NULL, 
		"CNOMBRE" VARCHAR(80) NOT NULL, 
		"CDSCPROGRAMA" VARCHAR(100) NOT NULL, 
		"LTIENEESCRITURA" SMALLINT NOT NULL DEFAULT 0, 
		"LCONFIGURABLE" SMALLINT NOT NULL DEFAULT 0, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0
	)
	DATA CAPTURE NONE 
	IN "SSEGPROGRAMA"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGPROPIEDAD" (
		"ICVESISTEMA" SMALLINT NOT NULL DEFAULT 0, 
		"CPROPIEDAD" VARCHAR(50) NOT NULL, 
		"CVALOR" VARCHAR(900) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SGRLDEPENDENCIA"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGSISTEMA" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEUSUARIO" BIGINT, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CDSCSISTEMA" VARCHAR(100) NOT NULL, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0
	)
	DATA CAPTURE NONE 
	IN "SSEGSISTEMA"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGUNIDADORG" (
		"ICVEUNIDADORG" SMALLINT NOT NULL, 
		"CDENOMINACION" VARCHAR(20) NOT NULL, 
		"CDESCRIPCIONBREVE" VARCHAR(10) NOT NULL, 
		"COBSERVACION" VARCHAR(50), 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0
	)
	DATA CAPTURE NONE 
	IN "SSEGUNIDADORG"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SEGUOXUSR" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"ICVEUNIDADORG" SMALLINT NOT NULL
	)
	DATA CAPTURE NONE 
	IN "SSEGUOXUSR"
	COMPRESS NO;


CREATE TABLE "ADMSEGDS"."SEGUSUARIO" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"DTREGISTRO" DATE, 
		"CUSUARIO" VARCHAR(25) NOT NULL, 
		"CPASSWORD" VARCHAR(15) NOT NULL, 
		"CNOMBRE" VARCHAR(50) NOT NULL, 
		"CAPPATERNO" VARCHAR(50) NOT NULL, 
		"CAPMATERNO" VARCHAR(20), 
		"CCALLE" VARCHAR(150) NOT NULL, 
		"CCOLONIA" VARCHAR(100), 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT, 
		"ICVEMUNICIPIO" BIGINT, 
		"ICODIGOPOSTAL" BIGINT, 
		"CTELEFONO" VARCHAR(15) NOT NULL, 
		"ICVEUNIDADORG" SMALLINT, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0, 
		"CECORREO" VARCHAR(100), 
		"DTCAMBIOCONTRA" DATE
	)
	DATA CAPTURE NONE 
	IN "SSEGUSUARIO"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."SU_ING" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"DTREGISTRO" DATE, 
		"CUSUARIO" VARCHAR(10) NOT NULL, 
		"CPASSWORD" VARCHAR(10) NOT NULL, 
		"CNOMBRE" VARCHAR(30) NOT NULL, 
		"CAPPATERNO" VARCHAR(20) NOT NULL, 
		"CAPMATERNO" VARCHAR(20), 
		"CCALLE" VARCHAR(100) NOT NULL, 
		"CCOLONIA" VARCHAR(70), 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT, 
		"ICVEMUNICIPIO" BIGINT, 
		"ICODIGOPOSTAL" BIGINT, 
		"CTELEFONO" VARCHAR(30) NOT NULL, 
		"ICVEUNIDADORG" SMALLINT, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."TMP_CING" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"SIGTIC" VARCHAR(20), 
		"CPASSSIGTIC" VARCHAR(30), 
		"CUSUARIO" VARCHAR(30), 
		"CPASSWORD" VARCHAR(30), 
		"NICVEUSUARIO" BIGINT
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."TMP_SEGGPOXUSR" (
		"ICVESEGXUSR" BIGINT, 
		"ICVESISTEMA" SMALLINT, 
		"ICVEUSUARIO" BIGINT, 
		"ICVEGRUPO" SMALLINT, 
		"CSISTEMA" VARCHAR(50) NOT NULL, 
		"CUSUARIO" VARCHAR(10) NOT NULL, 
		"CGRUPO" VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."TMP_SEGGRUPO" (
		"ICVEGPO" BIGINT, 
		"ICVESISTEMA" SMALLINT, 
		"ICVEGRUPO" SMALLINT, 
		"CDSCGRUPO" VARCHAR(20), 
		"LBLOQUEADO" SMALLINT, 
		"CDESCRIPCION" VARCHAR(20) NOT NULL, 
		"CSISTEMA" VARCHAR(50) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."TMP_SEGSISTEMA" (
		"ICVESISTEMA" BIGINT, 
		"ICVEUSUARIO" BIGINT, 
		"CNOMBRE" VARCHAR(50) NOT NULL, 
		"CDSCSISTEMA" VARCHAR(20) NOT NULL, 
		"LBLOQUEADO" SMALLINT NOT NULL, 
		"CUSUARIO" VARCHAR(10) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE TABLE "ADMSEGDS"."TMP_SEGUSUARIO" (
		"ICVEUSUARIO" BIGINT, 
		"DTREGISTRO" DATE, 
		"CUSUARIO" VARCHAR(10) NOT NULL, 
		"CPASSWORD" VARCHAR(10) NOT NULL, 
		"CNOMBRE" VARCHAR(50) NOT NULL, 
		"CAPPATERNO" VARCHAR(50) NOT NULL, 
		"CAPMATERNO" VARCHAR(20), 
		"CCALLE" VARCHAR(150) NOT NULL, 
		"CCOLONIA" VARCHAR(100), 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT, 
		"ICVEMUNICIPIO" BIGINT, 
		"ICODIGOPOSTAL" BIGINT, 
		"CTELEFONO" VARCHAR(15) NOT NULL, 
		"ICVEUNIDADORG" SMALLINT, 
		"LBLOQUEADO" SMALLINT NOT NULL
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;