--<ScriptOptions statementTerminator=";"/>

CONNECT TO ADMSEGDS;

CREATE INDEX "DB2ADMIN"."XIF1GRLDEPARTAMENT"
	ON "ADMSEGDS"."GRLDEPARTAMENTO_LIC"
	("ICVECENTROSCT"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."ARG_I1"
	ON "ADMSEGDS"."EXPLAIN_ARGUMENT"
	("EXPLAIN_TIME"		ASC, 
	  "EXPLAIN_LEVEL"		ASC, 
	  "STMTNO"		ASC, 
	  "SECTNO"		ASC, 
	  "OPERATOR_ID"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."EXP_DIAG_DAT_I1"
	ON "ADMSEGDS"."EXPLAIN_DIAGNOSTIC_DATA"
	("EXPLAIN_TIME"		ASC, 
	  "EXPLAIN_LEVEL"		ASC, 
	  "STMTNO"		ASC, 
	  "SECTNO"		ASC, 
	  "DIAGNOSTIC_ID"		ASC, 
	  "ORDINAL"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKGPOXUSR195"
	ON "ADMSEGDS"."SEGGPOXUSR"
	("ICVESISTEMA"		ASC, 
	  "ICVEGRUPO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKGPOXUSR204"
	ON "ADMSEGDS"."SEGGPOXUSR"
	("ICVEUSUARIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKGRLCENTROSSCT"
	ON "ADMSEGDS"."GRLCENTROSSCT"
	("ICVEPAIS"		ASC, 
	  "ICVEENTIDADFED"		ASC, 
	  "ICVEMUNICIPIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKGRUPO200"
	ON "ADMSEGDS"."SEGGRUPO"
	("ICVESISTEMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKMENU198"
	ON "ADMSEGDS"."SEGMENU"
	("ICVESISTEMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKMODULO577"
	ON "ADMSEGDS"."GRLMODULO"
	("ICVEPAIS"		ASC, 
	  "ICVEESTADO"		ASC, 
	  "ICVEMUNICIPIO"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKMODULO665"
	ON "ADMSEGDS"."GRLMODULO"
	("ICVEUNIMED"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKMUNICIPIO193"
	ON "ADMSEGDS"."GRLMUNICIPIO"
	("ICVEPAIS"		ASC, 
	  "ICVEENTIDADFED"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKPERMISOXGPO194"
	ON "ADMSEGDS"."SEGPERMISOXGPO"
	("ICVESISTEMA"		ASC, 
	  "ICVEGRUPO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKPERMISOXGPO197"
	ON "ADMSEGDS"."SEGPERMISOXGPO"
	("ICVESISTEMA"		ASC, 
	  "ICVEPROGRAMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKPERMISOXUSR196"
	ON "ADMSEGDS"."SEGPERMISOXUSR"
	("ICVESISTEMA"		ASC, 
	  "ICVEPROGRAMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKPERMISOXUSR203"
	ON "ADMSEGDS"."SEGPERMISOXUSR"
	("ICVEUSUARIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKPROGRAMA199"
	ON "ADMSEGDS"."SEGPROGRAMA"
	("ICVESISTEMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKSISTEMA202"
	ON "ADMSEGDS"."SEGSISTEMA"
	("ICVEUSUARIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKUNIMED344"
	ON "ADMSEGDS"."GRLUNIMED"
	("ICVEPAIS"		ASC, 
	  "ICVEESTADO"		ASC, 
	  "ICVEMUNICIPIO"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKUOXUSR201"
	ON "ADMSEGDS"."SEGUOXUSR"
	("ICVEUNIDADORG"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKUOXUSR205"
	ON "ADMSEGDS"."SEGUOXUSR"
	("ICVEUSUARIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKUSUARIO206"
	ON "ADMSEGDS"."SEGUSUARIO"
	("ICVEPAIS"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKUSUARIO207"
	ON "ADMSEGDS"."SEGUSUARIO"
	("ICVEPAIS"		ASC, 
	  "ICVEENTIDADFED"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKUSUARIO208"
	ON "ADMSEGDS"."SEGUSUARIO"
	("ICVEPAIS"		ASC, 
	  "ICVEENTIDADFED"		ASC, 
	  "ICVEMUNICIPIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."FKUSUARIO209"
	ON "ADMSEGDS"."SEGUSUARIO"
	("ICVEUNIDADORG"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."IDXGRLMODULO"
	ON "ADMSEGDS"."GRLMODULO"
	("CCLUES"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS YES;

CREATE INDEX "ADMSEGDS"."IDX_I1"
	ON "ADMSEGDS"."ADVISE_INDEX"
	("EXPLAIN_TIME"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."IDX_I2"
	ON "ADMSEGDS"."ADVISE_INDEX"
	("NAME"		ASC, 
	  "EXPLAIN_TIME"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."IDX_SEGUSUARIO"
	ON "ADMSEGDS"."SEGUSUARIO"
	("CUSUARIO"		ASC, 
	  "CPASSWORD"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."MQT_I1"
	ON "ADMSEGDS"."ADVISE_MQT"
	("EXPLAIN_TIME"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."MQT_I2"
	ON "ADMSEGDS"."ADVISE_MQT"
	("NAME"		ASC, 
	  "EXPLAIN_TIME"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."OBJ_I1"
	ON "ADMSEGDS"."EXPLAIN_OBJECT"
	("EXPLAIN_TIME"		ASC, 
	  "EXPLAIN_LEVEL"		ASC, 
	  "STMTNO"		ASC, 
	  "SECTNO"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."OPR_I1"
	ON "ADMSEGDS"."EXPLAIN_OPERATOR"
	("EXPLAIN_TIME"		ASC, 
	  "EXPLAIN_LEVEL"		ASC, 
	  "STMTNO"		ASC, 
	  "SECTNO"		ASC, 
	  "OPERATOR_ID"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."PRD_I1"
	ON "ADMSEGDS"."EXPLAIN_PREDICATE"
	("EXPLAIN_TIME"		ASC, 
	  "EXPLAIN_LEVEL"		ASC, 
	  "STMTNO"		ASC, 
	  "SECTNO"		ASC, 
	  "OPERATOR_ID"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."PRT_I1"
	ON "ADMSEGDS"."ADVISE_PARTITION"
	("EXPLAIN_TIME"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."STMT_I1"
	ON "ADMSEGDS"."EXPLAIN_STATEMENT"
	("EXPLAIN_TIME"		ASC, 
	  "EXPLAIN_LEVEL"		ASC, 
	  "STMTNO"		ASC, 
	  "SECTNO"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ADMSEGDS"."STM_I1"
	ON "ADMSEGDS"."EXPLAIN_STREAM"
	("EXPLAIN_TIME"		ASC, 
	  "EXPLAIN_LEVEL"		ASC, 
	  "STMTNO"		ASC, 
	  "SECTNO"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "DB2UPAMP"."IDX1301111823260"
	ON "ADMSEGDS"."GRLUSUMEDICOS"
	("ICVEUSUARIO"		ASC, 
	  "ICVEMODULO"		ASC, 
	  "ICVEUNIMED"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "DB2UPAMP"."IDX1301111828340"
	ON "ADMSEGDS"."GRLUSUMEDICOS"
	("ICVEUSUARIO"		ASC, 
	  "ICVEPROCESO"		ASC, 
	  "ICVEMODULO"		ASC, 
	  "ICVEUNIMED"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "EEMIC"."XIF1GRLDEPARTAMENT"
	ON "ADMSEGDS"."GRLDEPARTAMENTO"
	("ICVECENTROSCT"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE INDEX "ESIAF"."XIF1GRLCENTROSCT"
	ON "ADMSEGDS"."GRLCENTROSCT"
	("ICVEPAIS"		ASC, 
	  "ICVEENTIDADFED"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."AKGRLUNIMED01"
	ON "ADMSEGDS"."GRLUNIMED"
	("ICVEUNIMED"		ASC)
INCLUDE ("CDSCUNIMED", "ICVEPAIS", "ICVEESTADO", "ICVEMUNICIPIO")
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."AKSEGUSUARIO01"
	ON "ADMSEGDS"."SU_ING"
	("ICVEUSUARIO"		ASC, 
	  "CUSUARIO"		ASC, 
	  "CNOMBRE"		ASC, 
	  "CAPPATERNO"		ASC, 
	  "CAPMATERNO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."AKUSUARIO1"
	ON "ADMSEGDS"."SEGUSUARIO"
	("CUSUARIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."IDX110191754250000"
	ON "ADMSEGDS"."GRLMODULO"
	("ICVEUNIMED"		ASC, 
	  "ICVEMODULO"		ASC)
INCLUDE ("CDSCMODULO")
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."IDX1208010005590"
	ON "ADMSEGDS"."GRLDEPARTAMENTO_LIC"
	("ICVEDEPARTAMENTO"		ASC)
INCLUDE ("ICVEDEPTOLIC", "CPREFIJOLIC")
	PCTFREE 10
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS YES;

CREATE UNIQUE INDEX "ADMSEGDS"."IDX1208010018260"
	ON "ADMSEGDS"."GRLDEPARTAMENTO_LIC"
	("ICVEDEPARTAMENTO"		ASC)
INCLUDE ("CDSCDEPARTAMENTO")
	PCTFREE 10
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS YES;

CREATE UNIQUE INDEX "ADMSEGDS"."IDX1208010026030"
	ON "ADMSEGDS"."GRLDEPARTAMENTO_LIC"
	("ICVEDEPARTAMENTO"		ASC)
INCLUDE ("ICVECENTROSCT", "CDSCDEPARTAMENTO")
	PCTFREE 10
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS YES;

CREATE UNIQUE INDEX "ADMSEGDS"."PKGRLCENTROSSCT"
	ON "ADMSEGDS"."GRLCENTROSSCT"
	("ICVECENTROSCT"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKGRLDEPENDENCIA"
	ON "ADMSEGDS"."GRLDEPENDENCIA"
	("ICVEDEPENDENCIA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKGRLENTIDADFED"
	ON "ADMSEGDS"."GRLENTIDADFED"
	("ICVEPAIS"		ASC, 
	  "ICVEENTIDADFED"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKGRLMUNICIPIO"
	ON "ADMSEGDS"."GRLMUNICIPIO"
	("ICVEPAIS"		ASC, 
	  "ICVEENTIDADFED"		ASC, 
	  "ICVEMUNICIPIO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKGRLPAIS"
	ON "ADMSEGDS"."GRLPAIS"
	("ICVEPAIS"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKMODULO"
	ON "ADMSEGDS"."GRLMODULO"
	("ICVEUNIMED"		ASC, 
	  "ICVEMODULO"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKSECUENCIAS"
	ON "ADMSEGDS"."SECUENCIAS"
	("TABLA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKSEGGRUPO"
	ON "ADMSEGDS"."SEGGRUPO"
	("ICVESISTEMA"		ASC, 
	  "ICVEGRUPO"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKSEGMENU"
	ON "ADMSEGDS"."SEGMENU"
	("IORDEN"		ASC, 
	  "ICVESISTEMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKSEGPERMISOCGPO"
	ON "ADMSEGDS"."SEGPERMISOXGPO"
	("ICVESISTEMA"		ASC, 
	  "ICVEGRUPO"		ASC, 
	  "ICVEPROGRAMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKSEGPROGRAMA"
	ON "ADMSEGDS"."SEGPROGRAMA"
	("ICVESISTEMA"		ASC, 
	  "ICVEPROGRAMA"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKSEGPROPIEDAD"
	ON "ADMSEGDS"."SEGPROPIEDAD"
	("ICVESISTEMA"		ASC, 
	  "CPROPIEDAD"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKSEGUNIDADORG"
	ON "ADMSEGDS"."SEGUNIDADORG"
	("ICVEUNIDADORG"		ASC)
	PCTFREE 10
	MINPCTUSED 10
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ADMSEGDS"."PKUNIMED"
	ON "ADMSEGDS"."GRLUNIMED"
	("ICVEUNIMED"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "DB2INST3"."IDX108021915480000"
	ON "ADMSEGDS"."GRLDEPARTAMENTO"
	("ICVEDEPARTAMENTO"		ASC)
INCLUDE ("CDSCDEPARTAMENTO")
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "DB2UPAMP"."CC1113935093176"
	ON "ADMSEGDS"."GRLUSRXDEPTO_LIC"
	("ICVEUSUARIO"		ASC, 
	  "ICVEDEPARTAMENTO"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "DB2UPAMP"."PKUSUMEDICOS"
	ON "ADMSEGDS"."GRLUSUMEDICOS"
	("ICVEUSUARIO"		ASC, 
	  "ICVEUNIMED"		ASC, 
	  "ICVEPROCESO"		ASC, 
	  "ICVEMODULO"		ASC, 
	  "ICVESERVICIO"		ASC, 
	  "ICVERAMA"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;

CREATE UNIQUE INDEX "ESIAF"."XPKGRLCENTROSCT"
	ON "ADMSEGDS"."GRLCENTROSCT"
	("ICVECENTROSCT"		ASC)
	MINPCTUSED 0
	DISALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT STATISTICS
	COMPRESS NO;