--<ScriptOptions statementTerminator=";"/>

CONNECT TO ADMSEGDS;

ALTER TABLE "ADMSEGDS"."ADVISE_INSTANCE" ADD CONSTRAINT "SQL100412143004150" PRIMARY KEY
	("START_TIME");

ALTER TABLE "ADMSEGDS"."CATMODIFYBIT" ADD CONSTRAINT "SQL130808201934230" PRIMARY KEY
	("ICVEMODIFYBIT");

ALTER TABLE "ADMSEGDS"."EXPLAIN_DIAGNOSTIC" ADD CONSTRAINT "SQL100412143004080" PRIMARY KEY
	("EXPLAIN_REQUESTER", 
	 "EXPLAIN_TIME", 
	 "SOURCE_NAME", 
	 "SOURCE_SCHEMA", 
	 "SOURCE_VERSION", 
	 "EXPLAIN_LEVEL", 
	 "STMTNO", 
	 "SECTNO", 
	 "DIAGNOSTIC_ID");

ALTER TABLE "ADMSEGDS"."EXPLAIN_INSTANCE" ADD CONSTRAINT "SQL100412143003740" PRIMARY KEY
	("EXPLAIN_REQUESTER", 
	 "EXPLAIN_TIME", 
	 "SOURCE_NAME", 
	 "SOURCE_SCHEMA", 
	 "SOURCE_VERSION");

ALTER TABLE "ADMSEGDS"."EXPLAIN_STATEMENT" ADD CONSTRAINT "SQL100412143003870" PRIMARY KEY
	("EXPLAIN_REQUESTER", 
	 "EXPLAIN_TIME", 
	 "SOURCE_NAME", 
	 "SOURCE_SCHEMA", 
	 "SOURCE_VERSION", 
	 "EXPLAIN_LEVEL", 
	 "STMTNO", 
	 "SECTNO");


ALTER TABLE "ADMSEGDS"."GRLMODULO" ADD CONSTRAINT "SQL040713131425140" CHECK (LINTERCONSULTA BETWEEN 0 AND 1);

ALTER TABLE "ADMSEGDS"."GRLUNIMED" ADD CONSTRAINT "SQL040617112312350" CHECK (LCIS BETWEEN 0 AND 1)

ALTER TABLE "ADMSEGDS"."GRLUSRXDEPTO" ADD CONSTRAINT "CC1113935093176" PRIMARY KEY ("ICVEUSUARIO", "ICVEDEPARTAMENTO")

ALTER TABLE "ADMSEGDS"."GRLUSRXMDOTRANS" ADD CONSTRAINT "CC1146934049822" PRIMARY KEY ("ICVEUSUARIO", "ICVEMDOTRANS")

ALTER TABLE "ADMSEGDS"."PPEQUIPO" ADD CONSTRAINT "CC1281902534659" PRIMARY KEY ("ICVEPERSONA", "ICVEEQUIPO")

ALTER TABLE "ADMSEGDS"."PPUSRXPER" ADD CONSTRAINT "CC1284156285105" PRIMARY KEY ("ICVEPERSONA", "ICVEUSUARIO")

ALTER TABLE "ADMSEGDS"."PRYACTIVIDADES" ADD CONSTRAINT "CC1271186153548" PRIMARY KEY ("ICVEPROYECTO", "ICVEACTIVIDAD")

ALTER TABLE "ADMSEGDS"."PRYESTATUS" ADD CONSTRAINT "CC1271183479604" PRIMARY KEY ("ICVEESTATUS")

ALTER TABLE "ADMSEGDS"."PRYESTRUCTURA" ADD CONSTRAINT "CC1271183169784" PRIMARY KEY ("ICVEPROYECTO", "ICVEESTRUCTURA")

ALTER TABLE "ADMSEGDS"."PRYLOG" ADD CONSTRAINT "CC1271184367533" PRIMARY KEY ("ICVEPROYECTO", "ICVEACTIVIDAD", "TSREGISTRO")

ALTER TABLE "ADMSEGDS"."PRYPROYECTO" ADD CONSTRAINT "CC1271182700428" PRIMARY KEY ("ICVEPROYECTO")

ALTER TABLE "ADMSEGDS"."PRYUSUARIO" ADD CONSTRAINT "CC1271183810847" PRIMARY KEY ("ICVEPROYECTO", "ICVEUSUARIO")

ALTER TABLE "ADMSEGDS"."SEGBITMOD" ADD CONSTRAINT "SQL130808202003000" PRIMARY KEY ("ICVEBITMOD")

ALTER TABLE "ADMSEGDS"."SEGGPOXUSR" ADD CONSTRAINT "CC1110402706971" PRIMARY KEY ("ICVESISTEMA", "ICVEUSUARIO", "ICVEGRUPO")

ALTER TABLE "ADMSEGDS"."SEGPERMISOXUSR" ADD CONSTRAINT "CC1110403464990" PRIMARY KEY ("ICVEUSUARIO", "ICVESISTEMA", "ICVEPROGRAMA")

ALTER TABLE "ADMSEGDS"."SEGSISTEMA" ADD CONSTRAINT "CC1110403787967" PRIMARY KEY ("ICVESISTEMA")

ALTER TABLE "ADMSEGDS"."SEGUOXUSR" ADD CONSTRAINT "CC1110403903783" PRIMARY KEY ("ICVEUSUARIO", "ICVEUNIDADORG")

ALTER TABLE "ADMSEGDS"."SEGUSUARIO" ADD CONSTRAINT "CC1110400485492" PRIMARY KEY ("ICVEUSUARIO")

ALTER TABLE "ADMSEGDS"."SU_ING" ADD CONSTRAINT "PKSEGUSUARIO" PRIMARY KEY ("ICVEUSUARIO")

ALTER TABLE "ADMSEGDS"."ADVISE_INDEX" ADD CONSTRAINT "SQL100412143004180" FOREIGN KEY ("RUN_ID") REFERENCES "ADMSEGDS"."ADVISE_INSTANCE" ("START_TIME") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."ADVISE_MQT" ADD CONSTRAINT "SQL100412143004260" FOREIGN KEY ("RUN_ID") REFERENCES "ADMSEGDS"."ADVISE_INSTANCE" ("START_TIME") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."ADVISE_PARTITION" ADD CONSTRAINT "SQL100412143004290" FOREIGN KEY ("RUN_ID") REFERENCES "ADMSEGDS"."ADVISE_INSTANCE" ("START_TIME") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."ADVISE_TABLE" ADD CONSTRAINT "SQL100412143004320" FOREIGN KEY ("RUN_ID") REFERENCES "ADMSEGDS"."ADVISE_INSTANCE" ("START_TIME") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_ARGUMENT" ADD CONSTRAINT "SQL100412143003920" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") REFERENCES "ADMSEGDS"."EXPLAIN_STATEMENT" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_DIAGNOSTIC" ADD CONSTRAINT "SQL100412143004081" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") REFERENCES "ADMSEGDS"."EXPLAIN_STATEMENT" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_DIAGNOSTIC_DATA" ADD CONSTRAINT "SQL100412143004110" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO", "DIAGNOSTIC_ID") REFERENCES "ADMSEGDS"."EXPLAIN_DIAGNOSTIC" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO", "DIAGNOSTIC_ID") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_OBJECT" ADD CONSTRAINT "SQL100412143003960" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") REFERENCES "ADMSEGDS"."EXPLAIN_STATEMENT" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_OPERATOR" ADD CONSTRAINT "SQL100412143003980" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") REFERENCES "ADMSEGDS"."EXPLAIN_STATEMENT" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_PREDICATE" ADD CONSTRAINT "SQL100412143004000" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") REFERENCES "ADMSEGDS"."EXPLAIN_STATEMENT" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_STATEMENT" ADD CONSTRAINT "SQL100412143003880" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION") REFERENCES "ADMSEGDS"."EXPLAIN_INSTANCE" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION") ON DELETE CASCADE

ALTER TABLE "ADMSEGDS"."EXPLAIN_STREAM" ADD CONSTRAINT "SQL100412143004040" FOREIGN KEY ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") REFERENCES "ADMSEGDS"."EXPLAIN_STATEMENT" ("EXPLAIN_REQUESTER", "EXPLAIN_TIME", "SOURCE_NAME", "SOURCE_SCHEMA", "SOURCE_VERSION", "EXPLAIN_LEVEL", "STMTNO", "SECTNO") ON DELETE CASCADE


