INSERT INTO "SERVICOM"."GRLOFICINA" (ICVEOFICINA,CDSCOFICINA,CDSCBREVE,ICVECATEGORIA,ICVEPAIS,ICVEENTIDADFED,ICVEMUNICIPIO,CCALLEYNO,CCOLONIA,CCODPOSTAL,CTITULAR,CTELEFONO,CCORREOE,LVIGENTE,ICVEOFICINGRESOS,ICVEUNIDADMVA,ICVEOFICINACIS) VALUES (0,'NO ESPECIFICADO','(NO ESPECIFICADO)',0,1,1,1,'NO ESPECIFICADO','NO ESPECIFICADO','0','NO ESPECIFICADO','','',1,0,0,0);
INSERT INTO "SERVICOM"."GRLOFICINA" (ICVEOFICINA,CDSCOFICINA,CDSCBREVE,ICVECATEGORIA,ICVEPAIS,ICVEENTIDADFED,ICVEMUNICIPIO,CCALLEYNO,CCOLONIA,CCODPOSTAL,CTITULAR,CTELEFONO,CCORREOE,LVIGENTE,ICVEOFICINGRESOS,ICVEUNIDADMVA,ICVEOFICINACIS) VALUES (1,'OFICINA CENTRAL DE CIUDAD DE MEXICO','OFICINA CENTRAL DE CIUDAD DE MEXICO',0,1,9,15,'NUEVO LEON NO. 210 3° PISO','HIPODROMO CONDESA','','LIC. MARCOFLAVIO RIGADA SOTO','','',1,1,662,93);



INSERT INTO "SERVICOM"."GRLDEPARTAMENTO" (ICVEDEPARTAMENTO,CDSCDEPARTAMENTO,CDSCBREVE,LVIGENTE) VALUES (0,'(NO ESPECIFICADO)','(NO ESPECIFICADO)',1);
INSERT INTO "SERVICOM"."GRLDEPARTAMENTO" (ICVEDEPARTAMENTO,CDSCDEPARTAMENTO,CDSCBREVE,LVIGENTE) VALUES (1,'COORDINACIÓN GENERAL DE PUERTOS Y MARINA MERCANTE','COORD. GENERAL DE PUERTOS Y MARINA MERCANTE',1);
INSERT INTO "SERVICOM"."GRLDEPARTAMENTO" (ICVEDEPARTAMENTO,CDSCDEPARTAMENTO,CDSCBREVE,LVIGENTE) VALUES (95,'VENTANILLA UNICA','VENTANILLA UNICA',1);
INSERT INTO "SERVICOM"."GRLDEPARTAMENTO" (ICVEDEPARTAMENTO,CDSCDEPARTAMENTO,CDSCBREVE,LVIGENTE) VALUES (96,'DEPARTAMENTO DE ATENCIÓN DE TRÁMITES','DEPARTAMENTO DE ATENCIÓN DE TRÁMITES',1);


INSERT INTO "SERVICOM"."GRLUSUARIOXOFIC" (ICVEOFICINA,ICVEDEPARTAMENTO,ICVEUSUARIO,CTELEFONO,CCORREOE,LFIRMANTE) VALUES (1,95,1,null,null,0);
INSERT INTO "SERVICOM"."GRLUSUARIOXOFIC" (ICVEOFICINA,ICVEDEPARTAMENTO,ICVEUSUARIO,CTELEFONO,CCORREOE,LFIRMANTE) VALUES (1,96,1,null,null,0);


CREATE ALIAS DB2ADMIN.GRLOFICINA FOR SERVICOM.GRLOFICINA;
CREATE ALIAS DB2ADMIN.GRLDEPARTAMENTO FOR SERVICOM.GRLDEPARTAMENTO;
CREATE ALIAS DB2ADMIN.GRLUSUARIOXOFIC FOR SERVICOM.GRLUSUARIOXOFIC;