-<ScriptOptions statementTerminator=";"/>

CONNECT TO SERVICOM;

INSERT INTO "SERVICOM"."SEGUSUARIO" (ICVEUSUARIO,DTREGISTRO,CUSUARIO,CPASSWORD,CNOMBRE,CAPPATERNO,CAPMATERNO,CCALLE,CCOLONIA,ICVEPAIS,
									ICVEENTIDADFED,ICVEMUNICIPIO,ICODIGOPOSTAL,CTELEFONO,ICVEUNIDADORG,LBLOQUEADO,CECORREO) VALUES 
									(1,'2013-08-23','admin','admin','USUARIO','ADMINISTRADOR','DEL SISTEMA','AV INSURGENTES SUR #1089','NOCHE BUENA',1,9,9,3720,'54824180',1,0,null);
