CREATE TABLE "ADMSEGDS"."CATMODIFYBIT" (
		"ICVEMODIFYBIT" SMALLINT NOT NULL, 
		"CNOMBREMOD" VARCHAR(300) NOT NULL
	)

CREATE TABLE "ADMSEGDS"."GRLCENTROSCT" (
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"CDSCCSCT" VARCHAR(20) NOT NULL, 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT NOT NULL, 
		"ICVEUSUDIRECTOR" BIGINT, 
		"ICVEOFICINACIS" INTEGER, 
		"CTITULAR" VARCHAR(255), 
		"ICVEUNIDADADMING" INTEGER
	)

CREATE TABLE "ADMSEGDS"."GRLCENTROSSCT" (
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"ICVEPAIS" SMALLINT, 
		"ICVEENTIDADFED" SMALLINT, 
		"ICVEMUNICIPIO" SMALLINT, 
		"CDSCCENTROSCT" VARCHAR(25)
	)

CREATE TABLE "ADMSEGDS"."GRLDEPARTAMENTO" (
		"ICVEDEPARTAMENTO" INTEGER NOT NULL, 
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"ICVEOFICINAINGRESOS" INTEGER, 
		"CDSCDEPARTAMENTO" VARCHAR(255), 
		"ICVEOFICINACIS" INTEGER, 
		"CPREFIJOLIC" VARCHAR(5), 
		"ICVEDEPTOLIC" SMALLINT, 
		"ICVEAREARECAUDADORA" INTEGER, 
		"ICVECSCTINGRESOS" BIGINT, 
		"ICVEOFICINAINGRESO" INTEGER
	)


CREATE TABLE "ADMSEGDS"."GRLDEPARTAMENTO_LIC" (
		"ICVEDEPARTAMENTO" INTEGER NOT NULL, 
		"ICVECENTROSCT" SMALLINT NOT NULL, 
		"ICVEOFICINAINGRESO" INTEGER, 
		"CDSCDEPARTAMENTO" VARCHAR(255), 
		"ICVEOFICINACIS" INTEGER, 
		"CPREFIJOLIC" VARCHAR(5), 
		"ICVEDEPTOLIC" SMALLINT, 
		"LGENERADOCTOS" SMALLINT NOT NULL DEFAULT 0, 
		"CNOMFIRMADOCTO" VARCHAR(300), 
		"CPUESTOFIRMADOCTO" VARCHAR(300), 
		"CFIRMADOCTO" VARCHAR(60), 
		"CNOMFIRMAINGLES" VARCHAR(60), 
		"CPUESTOFIRMAINGLES" VARCHAR(300), 
		"ICVEUNIDADADMING" INTEGER DEFAULT 0, 
		"ICVECENTROSCTING" INTEGER DEFAULT 0, 
		"ICVEAREARECAUDING" INTEGER DEFAULT 0, 
		"LCIMPRESION" SMALLINT, 
		"CDEPTOSDET" VARCHAR(50), 
		"LINTERNET" SMALLINT
	)


CREATE TABLE "ADMSEGDS"."GRLDEPENDENCIA" (
		"ICVEDEPENDENCIA" SMALLINT NOT NULL, 
		"CDSCDEPENDENCIA" VARCHAR(25)
	)

CREATE TABLE "ADMSEGDS"."GRLENTIDADFED" (
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT NOT NULL, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CABREVIATURA" VARCHAR(30) NOT NULL
	)

CREATE TABLE "ADMSEGDS"."GRLMODULO" (
		"ICVEUNIMED" SMALLINT NOT NULL, 
		"ICVEMODULO" SMALLINT NOT NULL, 
		"CDSCMODULO" VARCHAR(100) NOT NULL, 
		"CCALLE" VARCHAR(50), 
		"CCOLONIA" VARCHAR(30), 
		"ICP" BIGINT NOT NULL, 
		"CCIUDAD" VARCHAR(50), 
		"ICVEPAIS" SMALLINT, 
		"ICVEESTADO" SMALLINT, 
		"ICVEMUNICIPIO" SMALLINT, 
		"CTEL" VARCHAR(20), 
		"CCORREOE" VARCHAR(100), 
		"LINTERCONSULTA" SMALLINT NOT NULL DEFAULT 0, 
		"LVIGENTE" SMALLINT NOT NULL, 
		"ICVEOFICINA" SMALLINT DEFAULT 1, 
		"CCLUES" VARCHAR(20), 
		"LVALIDA" SMALLINT DEFAULT 0
	)


CREATE TABLE "ADMSEGDS"."GRLMUNICIPIO" (
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT NOT NULL, 
		"ICVEMUNICIPIO" BIGINT NOT NULL, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CABREVIATURA" VARCHAR(30) NOT NULL
	)

CREATE TABLE "ADMSEGDS"."GRLPAIS" (
		"ICVEPAIS" SMALLINT NOT NULL, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CABREVIATURA" VARCHAR(30) NOT NULL
	)

CREATE TABLE "ADMSEGDS"."GRLUNIMED" (
		"ICVEUNIMED" SMALLINT NOT NULL, 
		"CDSCUNIMED" VARCHAR(30), 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEESTADO" SMALLINT NOT NULL, 
		"ICVEMUNICIPIO" SMALLINT NOT NULL, 
		"LCIS" SMALLINT DEFAULT 0, 
		"LPAGO" SMALLINT NOT NULL DEFAULT 0, 
		"CCALLE" VARCHAR(50), 
		"CCOLONIA" VARCHAR(30), 
		"ICP" BIGINT, 
		"CCIUDAD" VARCHAR(50), 
		"CTEL" VARCHAR(20), 
		"CCORREOE" VARCHAR(100), 
		"LPRIVADA" SMALLINT, 
		"LVIGENTE" SMALLINT NOT NULL, 
		"ICVEUSURESPUM" INTEGER DEFAULT 0, 
		"ICVEUDDADMIVA" VARCHAR(30), 
		"LLABORATORIO" DECIMAL(1 , 0)
	)

CREATE TABLE "ADMSEGDS"."GRLUSRXDEPTO" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEDEPARTAMENTO" INTEGER NOT NULL
	)

CREATE TABLE "ADMSEGDS"."GRLUSRXDEPTO_LIC" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEDEPARTAMENTO" INTEGER NOT NULL
	)

CREATE TABLE "ADMSEGDS"."GRLUSRXMDOTRANS" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEMDOTRANS" INTEGER NOT NULL
	)

CREATE TABLE "ADMSEGDS"."GRLUSUMEDICOS" (
		"ICVEUSUARIO" INTEGER NOT NULL, 
		"ICVEUNIMED" INTEGER NOT NULL, 
		"ICVEPROCESO" INTEGER NOT NULL, 
		"ICVEMODULO" INTEGER NOT NULL, 
		"ICVESERVICIO" INTEGER NOT NULL, 
		"ICVERAMA" INTEGER NOT NULL
	)