CREATE TABLE "ADMSEGDS"."SECUENCIAS" (
		"TABLA" VARCHAR(50) NOT NULL, 
		"INDICE" BIGINT
	)

CREATE TABLE "ADMSEGDS"."SEGBITMOD" (
		"ICVEBITMOD" BIGINT NOT NULL, 
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"TFECHAMOD" TIMESTAMP NOT NULL, 
		"ICVEMODIFYBIT" SMALLINT NOT NULL, 
		"ICVESISTEMA" SMALLINT, 
		"ICVEGRUPO" SMALLINT, 
		"ICVEPROGRAMA" SMALLINT, 
		"COBSERVACION" VARCHAR(500)
	)

CREATE TABLE "ADMSEGDS"."SEGGPOXUSR" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"ICVEGRUPO" SMALLINT NOT NULL
	)

CREATE TABLE "ADMSEGDS"."SEGGRUPO" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEGRUPO" SMALLINT NOT NULL, 
		"CDSCGRUPO" VARCHAR(30) NOT NULL, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0, 
		"LINTERNO" SMALLINT, 
		"LHORARIO" SMALLINT
	)

CREATE TABLE "ADMSEGDS"."SEGMENU" (
		"IORDEN" BIGINT NOT NULL, 
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"CDSCMENU" VARCHAR(100), 
		"CREFERENCIA" VARCHAR(200), 
		"IOPCPADRE" BIGINT, 
		"LBLOQUEADO" SMALLINT DEFAULT 0, 
		"CNOMPAGINA" VARCHAR(100), 
		"CCLASECSS" VARCHAR(50)
	)

CREATE TABLE "ADMSEGDS"."SEGPERMISOXGPO" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEGRUPO" SMALLINT NOT NULL, 
		"ICVEPROGRAMA" SMALLINT NOT NULL, 
		"LEJECUCION" SMALLINT NOT NULL DEFAULT 1, 
		"LACTUALIZACION" SMALLINT NOT NULL DEFAULT 1
	)

CREATE TABLE "ADMSEGDS"."SEGPERMISOXUSR" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEPROGRAMA" SMALLINT NOT NULL, 
		"LEJECUCION" SMALLINT NOT NULL DEFAULT 1, 
		"LACTUALIZACION" SMALLINT NOT NULL DEFAULT 1
	)

CREATE TABLE "ADMSEGDS"."SEGPROGRAMA" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEPROGRAMA" SMALLINT NOT NULL, 
		"CNOMBRE" VARCHAR(80) NOT NULL, 
		"CDSCPROGRAMA" VARCHAR(100) NOT NULL, 
		"LTIENEESCRITURA" SMALLINT NOT NULL DEFAULT 0, 
		"LCONFIGURABLE" SMALLINT NOT NULL DEFAULT 0, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0
	)

CREATE TABLE "ADMSEGDS"."SEGPROPIEDAD" (
		"ICVESISTEMA" SMALLINT NOT NULL DEFAULT 0, 
		"CPROPIEDAD" VARCHAR(50) NOT NULL, 
		"CVALOR" VARCHAR(900) NOT NULL
	)

REATE TABLE "ADMSEGDS"."SEGSISTEMA" (
		"ICVESISTEMA" SMALLINT NOT NULL, 
		"ICVEUSUARIO" BIGINT, 
		"CNOMBRE" VARCHAR(100) NOT NULL, 
		"CDSCSISTEMA" VARCHAR(100) NOT NULL, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0
	)

CREATE TABLE "ADMSEGDS"."SEGUNIDADORG" (
		"ICVEUNIDADORG" SMALLINT NOT NULL, 
		"CDENOMINACION" VARCHAR(20) NOT NULL, 
		"CDESCRIPCIONBREVE" VARCHAR(10) NOT NULL, 
		"COBSERVACION" VARCHAR(50), 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0
	)

CREATE TABLE "ADMSEGDS"."SEGUOXUSR" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"ICVEUNIDADORG" SMALLINT NOT NULL
	)

CREATE TABLE "ADMSEGDS"."SEGUSUARIO" (
		"ICVEUSUARIO" BIGINT NOT NULL, 
		"DTREGISTRO" DATE, 
		"CUSUARIO" VARCHAR(25) NOT NULL, 
		"CPASSWORD" VARCHAR(15) NOT NULL, 
		"CNOMBRE" VARCHAR(50) NOT NULL, 
		"CAPPATERNO" VARCHAR(50) NOT NULL, 
		"CAPMATERNO" VARCHAR(20), 
		"CCALLE" VARCHAR(150) NOT NULL, 
		"CCOLONIA" VARCHAR(100), 
		"ICVEPAIS" SMALLINT NOT NULL, 
		"ICVEENTIDADFED" SMALLINT, 
		"ICVEMUNICIPIO" BIGINT, 
		"ICODIGOPOSTAL" BIGINT, 
		"CTELEFONO" VARCHAR(15) NOT NULL, 
		"ICVEUNIDADORG" SMALLINT, 
		"LBLOQUEADO" SMALLINT NOT NULL DEFAULT 0, 
		"CECORREO" VARCHAR(100), 
		"DTCAMBIOCONTRA" DATE
	)