--<ScriptOptions statementTerminator=";"/>

CONNECT TO SERVICOM


CREATE TABLE SERVICOM.GLRFOLIO
(
   IEJERCICIOFOLIO smallint NOT NULL,
   INUMDIRECCION smallint NOT NULL,
   INUMDEPARTAMENTO smallint NOT NULL,
   ICONSECUTIVOFOLIO smallint NOT NULL,
   DTASIGNACIONFOLIO date,
   CONSTRAINT SQL070206224312150 PRIMARY KEY (IEJERCICIOFOLIO,INUMDIRECCION,INUMDEPARTAMENTO,ICONSECUTIVOFOLIO)
)
;

CREATE TABLE SERVICOM.GRLATRIBFORMATOREG
(
   IEJERCICIO smallint NOT NULL,
   ICVEFORMATOREG bigint NOT NULL,
   ICVEFORMATO smallint NOT NULL,
   ICVEATRIBUTO smallint NOT NULL,
   DVALORINICIAL decimal(14,2),
   DVALORFINAL decimal(14,2),
   LLOGICO smallint DEFAULT 0 NOT NULL,
   CDSCBREVE varchar(150),
   ICVEOBSERVACION bigint,
   CONSTRAINT SQL070206224312490 PRIMARY KEY (IEJERCICIO,ICVEFORMATOREG,ICVEFORMATO,ICVEATRIBUTO)
)
;

CREATE TABLE "ADMSEGDS"."SEGPERMISOXUSR" (
      "ICVEUSUARIO" BIGINT NOT NULL, 
      "ICVESISTEMA" SMALLINT NOT NULL, 
      "ICVEPROGRAMA" SMALLINT NOT NULL, 
      "LEJECUCION" SMALLINT NOT NULL DEFAULT 1, 
      "LACTUALIZACION" SMALLINT NOT NULL DEFAULT 1
   )
   ;
CREATE TABLE SERVICOM.GRLBANCO
(
   ICVEBANCO smallint PRIMARY KEY NOT NULL,
   CDSCBANCO varchar(30),
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.GRLBITACORA
(
   ICVEUSUARIO bigint NOT NULL,
   TSMOVIMIENTO timestamp NOT NULL,
   CTABLAAFECTA varchar(50) NOT NULL,
   CLLAVEREG varchar(50) NOT NULL,
   ITIPOMOV smallint NOT NULL,
   CONSTRAINT CC1266454043463 PRIMARY KEY (ICVEUSUARIO,TSMOVIMIENTO)
)
;
CREATE TABLE SERVICOM.GRLBITACORAMOV
(
   ICVEUSUARIO bigint NOT NULL,
   TSMOVIMIENTO timestamp NOT NULL,
   CREGISTRO varchar(500) NOT NULL,
   CONSTRAINT CC1266454592274 PRIMARY KEY (ICVEUSUARIO,TSMOVIMIENTO)
)
;
CREATE TABLE SERVICOM.GRLCATEGORIAOFIC
(
   ICVECATEGORIA smallint PRIMARY KEY NOT NULL,
   CDSCCATEGORIA varchar(30),
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.GRLCAUSAPNC
(
   ICVEPRODUCTO int NOT NULL,
   ICVECAUSAPNC smallint NOT NULL,
   CDSCCAUSAPNC varchar(150),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   LREQUISITO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224313210 PRIMARY KEY (ICVEPRODUCTO,ICVECAUSAPNC)
)
;
CREATE TABLE SERVICOM.GRLCONFIGCATFORMATO
(
   ICVEFORMATO smallint NOT NULL,
   ICVEATRIBUTO smallint NOT NULL,
   ICVEATRIBUTONIVELANTERIOR smallint,
   CTABLA varchar(50),
   CCAMPOLLAVE varchar(50),
   CCAMPOORDEN varchar(50),
   CJSPCONTROLADOR varchar(20),
   CONSTRAINT SQL070206224313850 PRIMARY KEY (ICVEFORMATO,ICVEATRIBUTO)
)
;
CREATE TABLE SERVICOM.GRLCONFIGFORMATO
(
   ICVEFORMATO smallint NOT NULL,
   ICVEATRIBUTO smallint NOT NULL,
   IORDEN smallint,
   CDSCATRIBUTO varchar(100),
   CETIQUETAANTERIOR varchar(100),
   ICVETIPORESPUESTA smallint,
   CETIQUETAPOSTERIOR varchar(100),
   LOBLIGATORIO smallint DEFAULT 0 NOT NULL,
   CVALORINIOMISION varchar(30),
   CVALORFINOMISION varchar(30),
   IMAXLONGITUD smallint,
   CNOMCAMPOPANTALLA varchar(50),
   CTABLAMAPEO varchar(30),
   CCAMPOMAPEO varchar(30),
   CJSVALIDACIONES varchar(20),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   IRENGLON smallint DEFAULT 0 NOT NULL,
   ICOLUMNA smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224314690 PRIMARY KEY (ICVEFORMATO,ICVEATRIBUTO)
)
;
CREATE TABLE SERVICOM.GRLDEPARTAMENTO
(
   ICVEDEPARTAMENTO smallint PRIMARY KEY NOT NULL,
   CDSCDEPARTAMENTO varchar(150),
   CDSCBREVE varchar(50),
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.GRLDEPTODEPEND
(
   ICVEOFICINA smallint NOT NULL,
   ICVEDEPARTAMENTO smallint NOT NULL,
   ICVEDEPTOHIJO smallint NOT NULL,
   CONSTRAINT SQL070206224315100 PRIMARY KEY (ICVEOFICINA,ICVEDEPARTAMENTO,ICVEDEPTOHIJO)
)
;
CREATE TABLE SERVICOM.GRLDEPTOXOFIC
(
   ICVEOFICINA smallint NOT NULL,
   ICVEDEPARTAMENTO smallint NOT NULL,
   CTITULAR varchar(100),
   CTELEFONO varchar(50),
   CCORREOE varchar(50),
   CPUESTOTITULAR varchar(100),
   CONSTRAINT SQL070206224315430 PRIMARY KEY (ICVEOFICINA,ICVEDEPARTAMENTO)
)
;
CREATE TABLE SERVICOM.GRLDIANOHABIL
(
   IEJERCICIO smallint NOT NULL,
   DTNOHABIL date NOT NULL,
   CDSCDIA varchar(30),
   CONSTRAINT SQL070206224315610 PRIMARY KEY (IEJERCICIO,DTNOHABIL)
)
;
CREATE TABLE SERVICOM.GRLDIGITOSFOLIOXDEPTO
(
   CDIGITOSFOLIO varchar(20) NOT NULL,
   DTASIGNACION date NOT NULL,
   ICVEOFICINA smallint NOT NULL,
   ICVEDEPARTAMENTO smallint NOT NULL,
   CONSTRAINT SQL070206224315810 PRIMARY KEY (CDIGITOSFOLIO,DTASIGNACION)
)
;
CREATE TABLE SERVICOM.GRLDOCFOLIOCM
(
   IEJERCICIO smallint NOT NULL,
   IIDGESTORDOCUMENTO bigint NOT NULL,
   CTABLACM varchar(30),
   CONSTRAINT SQL070206224316020 PRIMARY KEY (IEJERCICIO,IIDGESTORDOCUMENTO)
)
;
CREATE TABLE SERVICOM.GRLDOCREGISTRADO
(
   IEJERCICIO smallint NOT NULL,
   IIDGESTORDOCUMENTO bigint NOT NULL,
   BDOCALMACENADO blob(1048576),
   LACTIVO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224316190 PRIMARY KEY (IEJERCICIO,IIDGESTORDOCUMENTO)
)
;
CREATE TABLE SERVICOM.GRLDOCUMENTO
(
   IEJERCICIO smallint NOT NULL,
   ICVETIPODOCUMENTO smallint NOT NULL,
   IIDDOCUMENTO bigint NOT NULL,
   IIDGESTORDOCUMENTO bigint,
   ICVEUSUARIO bigint,
   DTREGISTRO date,
   CDSCDOCUMENTO varchar(50),
   COBSES varchar(200),
   CNOMARCHIVO varchar(100),
   CEXTENSIONARCHIVO varchar(30),
   LBASEGESTOR smallint DEFAULT 0,
   CMIMETYPE varchar(30),
   CONSTRAINT SQL070215163517320 PRIMARY KEY (IEJERCICIO,ICVETIPODOCUMENTO,IIDDOCUMENTO)
)
;
CREATE TABLE SERVICOM.GRLDOCUMENTOXSOL
(
   IEJERCICIO smallint NOT NULL,
   ICVETIPODOCUMENTO smallint NOT NULL,
   IIDDOCUMENTO bigint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   CONSTRAINT SQL100910123603380 PRIMARY KEY (IEJERCICIO,ICVETIPODOCUMENTO,IIDDOCUMENTO,INUMSOLICITUD)
)
;
CREATE TABLE SERVICOM.GRLDOMICILIO
(
   ICVEPERSONA bigint NOT NULL,
   ICVEDOMICILIO smallint NOT NULL,
   ICVETIPODOMICILIO smallint,
   CCALLE varchar(100),
   CNUMEXTERIOR varchar(20),
   CNUMINTERIOR varchar(20),
   CCOLONIA varchar(75),
   CCODPOSTAL varchar(5),
   CTELEFONO varchar(50),
   ICVEPAIS smallint,
   ICVEENTIDADFED smallint,
   ICVEMUNICIPIO smallint,
   ICVELOCALIDAD smallint,
   LPREDETERMINADO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224317040 PRIMARY KEY (ICVEPERSONA,ICVEDOMICILIO)
)
;
CREATE TABLE SERVICOM.GRLENTIDADFED
(
   ICVEPAIS smallint NOT NULL,
   ICVEENTIDADFED smallint NOT NULL,
   CNOMBRE varchar(50),
   CABREVIATURA varchar(20),
   CONSTRAINT SQL070206224317250 PRIMARY KEY (ICVEPAIS,ICVEENTIDADFED)
)
;
CREATE TABLE SERVICOM.GRLFOLIO
(
   IEJERCICIO smallint NOT NULL,
   ICVEOFICINA smallint NOT NULL,
   ICVEDEPARTAMENTO smallint NOT NULL,
   CDIGITOSFOLIO varchar(20) NOT NULL,
   ICONSECUTIVO smallint NOT NULL,
   DTASIGNACION date,
   ICVEUSUASIGNA bigint,
   CDIRIGIDOA varchar(100),
   CASUNTO varchar(200),
   CTITULARFIRMA varchar(100),
   DTENVIO date,
   DTRECEPCION date,
   CNUMOFICIALIAPARTES varchar(15),
   CNUMCONTROLGESTION varchar(15),
   DTCANCELACION date,
   ICVEUSUCANCELA bigint,
   CMOTIVOCANCELA varchar(200),
   CONSTRAINT SQL070215163518860 PRIMARY KEY (IEJERCICIO,ICVEOFICINA,ICVEDEPARTAMENTO,CDIGITOSFOLIO,ICONSECUTIVO)
)
;
CREATE TABLE SERVICOM.GRLFOLIOXSEGTOENT
(
   ICVESEGTOENTIDAD bigint NOT NULL,
   ICONSECUTIVOSEGTOREF smallint NOT NULL,
   LFOLIOREFERENINTERNO smallint DEFAULT 0 NOT NULL,
   CNUMOFPARTESREFEXTERNA varchar(15),
   CNUMOFICIOREFEXTERNA varchar(20),
   IEJERCICIOFOLIO smallint,
   ICVEOFICINA smallint,
   ICVEDEPARTAMENTO smallint,
   CDIGITOSFOLIO varchar(10),
   ICONSECUTIVO smallint,
   LEXTERNO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224320070 PRIMARY KEY (ICVESEGTOENTIDAD,ICONSECUTIVOSEGTOREF)
)
;
CREATE TABLE SERVICOM.GRLFORMATO
(
   ICVEFORMATO smallint PRIMARY KEY NOT NULL,
   CDSCFORMATO varchar(150),
   CTITULO varchar(75),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   DTINIVIGENCIA date,
   CTABLABUSCA varchar(30),
   CCAMPOLLAVEBUSCA varchar(30),
   INUMCOLUMNAS smallint
)
;
CREATE TABLE SERVICOM.GRLFORMATOSALIDA
(
   ICVEFORMATOSALIDA int PRIMARY KEY NOT NULL,
   CDSCFORMATOSALIDA varchar(100),
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.GRLLOCALIDAD
(
   ICVEPAIS smallint NOT NULL,
   ICVEENTIDADFED smallint NOT NULL,
   ICVEMUNICIPIO smallint NOT NULL,
   ICVELOCALIDAD smallint NOT NULL,
   CNOMBRE varchar(100),
   CABREVIATURA varchar(30),
   CONSTRAINT SQL070206224322410 PRIMARY KEY (ICVEPAIS,ICVEENTIDADFED,ICVEMUNICIPIO,ICVELOCALIDAD)
)
;
CREATE TABLE SERVICOM.GRLMIMETYPE
(
   CMIMETYPE varchar(30) PRIMARY KEY NOT NULL,
   CEXTENSIONES varchar(100)
)
;
CREATE TABLE SERVICOM.GRLMODTIPODOCUMENTO
(
   ICVESISTEMA smallint NOT NULL,
   ICVEMODULO smallint NOT NULL,
   ICVETIPODOCUMENTO smallint NOT NULL,
   CONSTRAINT SQL070206224323380 PRIMARY KEY (ICVESISTEMA,ICVEMODULO,ICVETIPODOCUMENTO)
)
;
CREATE TABLE SERVICOM.GRLMODULO
(
   ICVESISTEMA smallint NOT NULL,
   ICVEMODULO smallint NOT NULL,
   CDSCMODULO varchar(100),
   LACTIVO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224323590 PRIMARY KEY (ICVESISTEMA,ICVEMODULO)
)
;
CREATE TABLE SERVICOM.GRLMOTIVOCANCELA
(
   ICVEMOTIVOCANCELA smallint PRIMARY KEY NOT NULL,
   CDSCMOTIVO varchar(150),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   LASIGNAVU smallint DEFAULT 0,
   LASIGNAAREA smallint DEFAULT 0
)
;
CREATE TABLE SERVICOM.GRLMUNICIPIO
(
   ICVEPAIS smallint NOT NULL,
   ICVEENTIDADFED smallint NOT NULL,
   ICVEMUNICIPIO smallint NOT NULL,
   CNOMBRE varchar(50),
   CABREVIATURA varchar(20),
   CONSTRAINT SQL070206224324000 PRIMARY KEY (ICVEPAIS,ICVEENTIDADFED,ICVEMUNICIPIO)
)
;
CREATE TABLE SERVICOM.GRLOBSERVACION
(
   IEJERCICIO smallint NOT NULL,
   ICVEOBSERVACION bigint NOT NULL,
   COBSREGISTRADA varchar(2000),
   CONSTRAINT SQL070206224324160 PRIMARY KEY (IEJERCICIO,ICVEOBSERVACION)
)
;
CREATE TABLE SERVICOM.GRLOBSERVALARGA
(
   IEJERCICIOOBSLARGA smallint NOT NULL,
   ICVEOBSLARGA bigint NOT NULL,
   CDSCOBSLARGA long varchar,
   CONSTRAINT SQL070206230749940 PRIMARY KEY (IEJERCICIOOBSLARGA,ICVEOBSLARGA)
)
;
CREATE TABLE SERVICOM.GRLOFICINA
(
   ICVEOFICINA smallint PRIMARY KEY NOT NULL,
   CDSCOFICINA varchar(150),
   CDSCBREVE varchar(50),
   ICVECATEGORIA smallint,
   ICVEPAIS smallint,
   ICVEENTIDADFED smallint,
   ICVEMUNICIPIO smallint,
   CCALLEYNO varchar(100),
   CCOLONIA varchar(75),
   CCODPOSTAL varchar(5),
   CTITULAR varchar(100),
   CTELEFONO varchar(50),
   CCORREOE varchar(50),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   ICVEOFICINGRESOS smallint,
   ICVEUNIDADMVA smallint,
   ICVEOFICINACIS int DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.GRLPAIS
(
   ICVEPAIS smallint PRIMARY KEY NOT NULL,
   CNOMBRE varchar(50),
   CABREVIATURA varchar(20)
)
;
CREATE TABLE SERVICOM.GRLPERSONA
(
   ICVEPERSONA bigint PRIMARY KEY NOT NULL,
   CRFC varchar(13),
   CRPA varchar(15),
   ITIPOPERSONA smallint,
   CNOMRAZONSOCIAL varchar(150),
   CAPPATERNO varchar(30),
   CAPMATERNO varchar(30),
   CCORREOE varchar(50),
   CPSEUDONIMOEMP varchar(50),
   CCURP varchar(25)
)
;
CREATE TABLE SERVICOM.GRLPROCESO
(
   ICVEPROCESO smallint PRIMARY KEY NOT NULL,
   CDSCPROCESO varchar(200),
   ICVETRAMITE smallint,
   ICVEMODALIDAD smallint,
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   LPROCESOCERTIFICADO smallint DEFAULT 0 NOT NULL,
   CDSCCERTIFICACION varchar(75)
)
;
CREATE TABLE SERVICOM.GRLPRODUCTO
(
   ICVEPRODUCTO int PRIMARY KEY NOT NULL,
   CDSCPRODUCTO varchar(150),
   CDSCBREVE varchar(50),
   LREQFIRMADIGITAL smallint DEFAULT 0 NOT NULL,
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.GRLPRODXOFICDEPTO
(
   ICVEOFICINA smallint NOT NULL,
   ICVEDEPARTAMENTO smallint NOT NULL,
   ICVEPROCESO smallint NOT NULL,
   ICVEPRODUCTO int NOT NULL,
   DTINIASIGNACION date,
   ICVEFORMATOSALIDA int,
   CONSTRAINT SQL070206224326810 PRIMARY KEY (ICVEOFICINA,ICVEDEPARTAMENTO,ICVEPROCESO,ICVEPRODUCTO)
)
;
CREATE TABLE SERVICOM.GRLREGCAUSAPNC
(
   IEJERCICIO smallint NOT NULL,
   ICONSECUTIVOPNC bigint NOT NULL,
   ICVEPRODUCTO int NOT NULL,
   ICVECAUSAPNC smallint NOT NULL,
   ICVEUSUCORRIGE bigint,
   CDSCOTRACAUSA varchar(500),
   LRESUELTO smallint DEFAULT 0 NOT NULL,
   DTRESOLUCION date,
   ICVEOFICINA smallint,
   ICVEDEPARTAMENTO smallint,
   ICVEPROCESO smallint,
   COBSLEY1 varchar(50),
   COBSLEY2 varchar(50),
   COBSLEY3 varchar(50),
   CONSTRAINT SQL070215163519940 PRIMARY KEY (IEJERCICIO,ICONSECUTIVOPNC,ICVEPRODUCTO,ICVECAUSAPNC)
)
;
CREATE TABLE SERVICOM.GRLREGISTROPNC
(
   IEJERCICIO smallint NOT NULL,
   ICONSECUTIVOPNC bigint NOT NULL,
   DTREGISTRO date,
   ICVEUSUREGISTRO bigint,
   ICVEPRODUCTO int,
   LRESUELTO smallint DEFAULT 0 NOT NULL,
   DTRESOLUCION date,
   ICVEOFICINAASIGNADO smallint,
   ICVEDEPTOASIGNADO smallint,
   ICVEOFICINA smallint,
   ICVEDEPARTAMENTO smallint,
   ICVEPROCESO smallint,
   CRECIBENOTIF varchar(100),
   DTOFICIO date,
   CNUMOFICIO varchar(20),
   DTNOTIFICACION date,
   CONSTRAINT SQL070215163520910 PRIMARY KEY (IEJERCICIO,ICONSECUTIVOPNC)
)
;
CREATE TABLE SERVICOM.GRLREPLEGAL
(
   ICVEEMPRESA bigint NOT NULL,
   ICVEPERSONA bigint NOT NULL,
   DTASIGNACION date,
   LPRINCIPAL smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224329180 PRIMARY KEY (ICVEEMPRESA,ICVEPERSONA)
)
;
CREATE TABLE SERVICOM.GRLREPORTE
(
   ICVESISTEMA smallint NOT NULL,
   ICVEMODULO smallint NOT NULL,
   INUMREPORTE smallint NOT NULL,
   CNOMREPORTE varchar(150),
   LEXCEL smallint DEFAULT 0 NOT NULL,
   LWORD smallint DEFAULT 0 NOT NULL,
   LPDF smallint DEFAULT 0 NOT NULL,
   LMULTIPART smallint DEFAULT 0 NOT NULL,
   CPLANTILLAEXCEL varchar(30),
   CPLANTILLAWORD varchar(30),
   CPLANTILLAPDF varchar(30),
   CDAOEJECUTAR varchar(30),
   CMETODOEXCEL varchar(50),
   CMETODOWORD varchar(50),
   CMETODOPDF varchar(50),
   ICVEFORMATOFILTRO smallint,
   LAUTOIMPRIMIR smallint DEFAULT 0 NOT NULL,
   INUMCOPIAS smallint,
   LMOSTRARAPLICACION smallint DEFAULT 0 NOT NULL,
   LPARAMETROMODIFICABLE smallint DEFAULT 0 NOT NULL,
   LREQUIEREFOLIO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224329880 PRIMARY KEY (ICVESISTEMA,ICVEMODULO,INUMREPORTE)
)
;
CREATE TABLE SERVICOM.GRLREPORTEXFOLIO
(
   IEJERCICIOFOLIO smallint NOT NULL,
   ICVEOFICINA smallint NOT NULL,
   ICVEDEPARTAMENTO smallint NOT NULL,
   CDIGITOSFOLIO varchar(20) NOT NULL,
   ICONSECUTIVO smallint NOT NULL,
   IEJERCICIOSOLICITUD smallint,
   INUMSOLICITUD bigint,
   ICVESISTEMA smallint NOT NULL,
   ICVEMODULO smallint NOT NULL,
   INUMREPORTE smallint NOT NULL,
   CONSTRAINT SQL070206224330240 PRIMARY KEY (IEJERCICIOFOLIO,ICVEOFICINA,ICVEDEPARTAMENTO,CDIGITOSFOLIO,ICONSECUTIVO)
)
;
CREATE TABLE SERVICOM.GRLSEGUIMIENTOPNC
(
   IEJERCICIO smallint NOT NULL,
   ICONSECUTIVOPNC bigint NOT NULL,
   ICVEPRODUCTO int NOT NULL,
   ICVECAUSAPNC smallint NOT NULL,
   ICVESEGUIMIENTO smallint NOT NULL,
   TSMOMENTOSEGUIMIENTO timestamp,
   CCOMENTARIOS varchar(1000),
   ICVEUSUREGISTRA bigint,
   ICVEOFICINAASIGNADO smallint,
   ICVEDEPTOASIGNADO smallint,
   CONSTRAINT SQL070215163521630 PRIMARY KEY (IEJERCICIO,ICONSECUTIVOPNC,ICVEPRODUCTO,ICVECAUSAPNC,ICVESEGUIMIENTO)
)
;
CREATE TABLE SERVICOM.GRLTIPODOCUMENTO
(
   ICVETIPODOCUMENTO smallint PRIMARY KEY NOT NULL,
   CDSCTIPODOCUMENTO varchar(50),
   LACTIVO smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.GRLTIPODOMICILIO
(
   ICVETIPODOMICILIO smallint PRIMARY KEY NOT NULL,
   CDSCTIPODOMICILIO varchar(30)
)
;
CREATE TABLE SERVICOM.GRLUSRXMODULO
(
   ICVESISTEMA int NOT NULL,
   ICVEMODULO smallint NOT NULL,
   ICVEUSUARIO bigint NOT NULL
)
;
CREATE TABLE SERVICOM.GRLUSUARIOXOFIC
(
   ICVEOFICINA smallint NOT NULL,
   ICVEDEPARTAMENTO smallint NOT NULL,
   ICVEUSUARIO bigint NOT NULL,
   CTELEFONO varchar(50),
   CCORREOE varchar(50),
   LFIRMANTE smallint,
   CONSTRAINT SQL070216092508550 PRIMARY KEY (ICVEOFICINA,ICVEDEPARTAMENTO,ICVEUSUARIO)
)
;
CREATE TABLE SERVICOM.INTCAMPOS
(
   ICVECAMPO int PRIMARY KEY NOT NULL,
   CCAMPO varchar(75),
   CETIQUETA varchar(75),
   ILARGO int,
   ICVETIPOCAMPO int,
   CTABLA varchar(75),
   CCVE varchar(256),
   CDSC varchar(512),
   LMANDATORIO smallint,
   LFIJO smallint,
   LENCABEZADO smallint,
   LSELECCIONAR smallint,
   CLIGADO varchar(100),
   CCAMPOCOP varchar(100),
   CSCRIPT varchar(350),
   CCARPETA varchar(50)
)
;
CREATE TABLE SERVICOM.INTTRAMXCAMPO
(
   ICVECAMPO int NOT NULL,
   IORDEN smallint,
   CCARPETA varchar(50),
   ICVETRAMITE int NOT NULL,
   ICVEMODALIDAD int NOT NULL,
   ICVEREQUISITO char(18) NOT NULL,
   CONSTRAINT XPKINTTRAMXCAMPO PRIMARY KEY (ICVECAMPO,ICVETRAMITE,ICVEMODALIDAD,ICVEREQUISITO)
)
;
CREATE TABLE SERVICOM.SEGGPOXUSR
(
   ICVESISTEMA smallint NOT NULL,
   ICVEUSUARIO bigint NOT NULL,
   ICVEGRUPO smallint NOT NULL,
   CONSTRAINT CC1110402706971 PRIMARY KEY (ICVESISTEMA,ICVEUSUARIO,ICVEGRUPO)
)
;
CREATE TABLE SERVICOM.SEGGRUPO
(
   ICVESISTEMA smallint NOT NULL,
   ICVEGRUPO smallint NOT NULL,
   CDSCGRUPO varchar(20) NOT NULL,
   LBLOQUEADO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT CC1110402783738 PRIMARY KEY (ICVESISTEMA,ICVEGRUPO)
)
;
CREATE TABLE SERVICOM.SEGPROGRAMA
(
   ICVESISTEMA smallint NOT NULL,
   ICVEPROGRAMA smallint NOT NULL,
   CNOM varchar(50),
   CDSCPROGRAMA varchar(50),
   LTIENEESCRITURA smallint DEFAULT 0 NOT NULL,
   LCONFIGURABLE smallint DEFAULT 0 NOT NULL,
   LBLOQUEADO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070206224332490 PRIMARY KEY (ICVESISTEMA,ICVEPROGRAMA)
)
;
CREATE TABLE SERVICOM.SEGSISTEMA
(
   ICVESISTEMA smallint PRIMARY KEY NOT NULL,
   ICVEUSUARIO bigint,
   CNOMBRE varchar(50),
   CDSCSISTEMA varchar(20),
   LBLOQUEADO smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.SEGUSUARIO
(
   ICVEUSUARIO bigint PRIMARY KEY NOT NULL,
   DTREGISTRO date,
   CUSUARIO varchar(10),
   CPASSWORD varchar(10),
   CNOMBRE varchar(30),
   CAPPATERNO varchar(20),
   CAPMATERNO varchar(20),
   CCALLE varchar(75),
   CCOLONIA varchar(50),
   ICVEPAIS smallint,
   ICVEENTIDADFED smallint,
   ICVEMUNICIPIO smallint,
   ICODIGOPOSTAL bigint,
   CTELEFONO varchar(15),
   ICVEUNIDADORG smallint,
   LBLOQUEADO smallint DEFAULT 0 NOT NULL,
   CECORREO varchar(100)
)
;
CREATE TABLE SERVICOM.TRACARACXREQUISITO
(
   ICVEREQUISITO smallint NOT NULL,
   ICVECARACTERISTICA smallint NOT NULL,
   CDSCCARACTERISTICA varchar(150),
   CDSCBREVE varchar(50),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   LENRECEPCION smallint DEFAULT 0 NOT NULL,
   LENPROCESO smallint DEFAULT 0 NOT NULL,
   LMANDATORIO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070207015512970 PRIMARY KEY (ICVEREQUISITO,ICVECARACTERISTICA)
)
;
CREATE TABLE SERVICOM.TRACATTRAMITE
(
   ICVETRAMITE smallint PRIMARY KEY NOT NULL,
   CCVEINTERNA varchar(10),
   CDSCTRAMITE varchar(500),
   CDSCBREVE varchar(100),
   LREQFIRMADIGITAL smallint DEFAULT 0 NOT NULL,
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   CBIENBUSCAR varchar(25),
   COBJETIVOTRAMITE varchar(1000),
   CCOMPROBANTE varchar(500),
   CNOTAS varchar(1200),
   LIMPRIMEMANUAL smallint DEFAULT 1 NOT NULL,
   ICVEMODULO int,
   ICVETRAMITEPADRE int,
   LTRAMITEFINAL int,
   ICVEUSUARIO int,
   TSMODIFICACION timestamp
)
;
CREATE TABLE SERVICOM.TRACOFEMER
(
   IEJERCICIO smallint NOT NULL,
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   CCVECOFEMER varchar(50),
   CONSTRAINT SQL070207015513890 PRIMARY KEY (IEJERCICIO,ICVETRAMITE,ICVEMODALIDAD)
)
;
CREATE TABLE SERVICOM.TRACONCEPTOPAGO
(
   ICVECONCEPTO smallint PRIMARY KEY NOT NULL,
   CDSCCONCEPTO varchar(150),
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.TRACONCEPTOXGRUPO
(
   ICVEGRUPO smallint NOT NULL,
   ICVECONCEPTO smallint NOT NULL,
   DLIMITEINFERIOR decimal(14,4),
   DLIMITESUPERIOR decimal(14,4),
   CONSTRAINT SQL070207015514440 PRIMARY KEY (ICVEGRUPO,ICVECONCEPTO)
)
;
CREATE TABLE SERVICOM.TRACONCEPTOXTIPOIN
(
   ICVECONCEPTO smallint NOT NULL,
   ICVEGRUPOCERTIF smallint NOT NULL,
   ITIPOCERTIFICADO smallint NOT NULL,
   LACTIVO smallint DEFAULT 0,
   CONSTRAINT SQL111011200926350 PRIMARY KEY (ICVECONCEPTO,ICVEGRUPOCERTIF,ITIPOCERTIFICADO)
)
;
CREATE TABLE SERVICOM.TRACONCEPTOXTRAMMOD
(
   IEJERCICIO smallint NOT NULL,
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVECONCEPTO smallint NOT NULL,
   LPAGOANTICIPADO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070207015514760 PRIMARY KEY (IEJERCICIO,ICVETRAMITE,ICVEMODALIDAD,ICVECONCEPTO)
)
;
CREATE TABLE SERVICOM.TRACONFIGURATRAMITE
(
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   DTINIVIGENCIA date NOT NULL,
   INUMDIASRESOL smallint,
   LDIASNATURALESRESOL smallint DEFAULT 0 NOT NULL,
   INUMDIASCUBRIRREQ smallint,
   LDIASNATURALESREQ smallint DEFAULT 0 NOT NULL,
   LREQUIEREPAGO smallint DEFAULT 0 NOT NULL,
   ICVEFORMATO smallint,
   ICVETRAMITECIS int DEFAULT 0 NOT NULL,
   CNOTAS varchar(1200),
   IDIASDESPUESNOTIF smallint,
   LACTIVO smallint DEFAULT 1,
   ICVEUSUARIO int,
   TSMODIFICACION timestamp,
   LTRAMINT smallint,
   CONSTRAINT SQL070207015515300 PRIMARY KEY (ICVETRAMITE,ICVEMODALIDAD,DTINIVIGENCIA)
)
;
CREATE TABLE SERVICOM.TRADATOSCITA
(
   IEJERCICIO smallint NOT NULL,
   IIDCITA bigint NOT NULL,
   DTCITA date,
   IEJERCICIOCITACIS int,
   COLUMNIIDCITACIS int,
   DTCITACIS date,
   CONSTRAINT SQL070207015515470 PRIMARY KEY (IEJERCICIO,IIDCITA)
)
;
CREATE TABLE SERVICOM.TRADEPENDENCIA
(
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVETRAMITEHIJO smallint NOT NULL,
   ICVEMODALIDADHIJO smallint NOT NULL,
   CONSTRAINT SQL070216090034660 PRIMARY KEY (ICVETRAMITE,ICVEMODALIDAD,ICVETRAMITEHIJO,ICVEMODALIDADHIJO)
)
;
CREATE TABLE SERVICOM.TRADOCTOTRAMITE
(
   IEJERCICIOSOLICITUD smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   IEJERCICIO smallint NOT NULL,
   ICVETIPODOCUMENTO smallint NOT NULL,
   IIDDOCUMENTO bigint NOT NULL,
   CONSTRAINT SQL070207015515960 PRIMARY KEY (IEJERCICIOSOLICITUD,INUMSOLICITUD,IEJERCICIO,ICVETIPODOCUMENTO,IIDDOCUMENTO)
)
;
CREATE TABLE SERVICOM.TRADOCTOXOPINION
(
   IEJERCICIOSOLICITUD smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVEOPINIONENTIDAD smallint NOT NULL,
   ICVESEGTOENTIDAD bigint NOT NULL,
   IEJERCICIO smallint NOT NULL,
   ICVETIPODOCUMENTO smallint NOT NULL,
   IIDDOCUMENTO bigint NOT NULL,
   CONSTRAINT SQL070207015516310 PRIMARY KEY (IEJERCICIOSOLICITUD,INUMSOLICITUD,ICVEOPINIONENTIDAD,ICVESEGTOENTIDAD,IEJERCICIO,ICVETIPODOCUMENTO,IIDDOCUMENTO)
)
;
CREATE TABLE SERVICOM.TRADOCXREQUIS
(
   IEJERCICIOREQ smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVEREQUISITO smallint NOT NULL,
   IEJERCICIO smallint NOT NULL,
   ICVETIPODOCUMENTO smallint NOT NULL,
   IIDDOCUMENTO bigint NOT NULL,
   CONSTRAINT SQL070207015516680 PRIMARY KEY (IEJERCICIOREQ,INUMSOLICITUD,ICVETRAMITE,ICVEMODALIDAD,ICVEREQUISITO,IEJERCICIO,ICVETIPODOCUMENTO,IIDDOCUMENTO)
)
;
CREATE TABLE SERVICOM.TRAETAPA
(
   ICVEETAPA smallint PRIMARY KEY NOT NULL,
   CDSCETAPA varchar(150),
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.TRAETAPAVINCULADA
(
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVETRAMITEHIJO smallint NOT NULL,
   ICVEMODALIDADHIJO smallint NOT NULL,
   ICVEETAPA smallint NOT NULL,
   ICVEETAPAVINC int,
   CONSTRAINT SQL100921184550200 PRIMARY KEY (ICVETRAMITE,ICVEMODALIDAD,ICVETRAMITEHIJO,ICVEMODALIDADHIJO,ICVEETAPA)
)
;
CREATE TABLE SERVICOM.TRAETAPAXMODTRAM
(
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVEETAPA smallint NOT NULL,
   IORDEN smallint,
   LOBLIGATORIO smallint DEFAULT 0 NOT NULL,
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   ICVEETAPACIS int DEFAULT 0 NOT NULL,
   LENVIARFECHACIS smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070207015517260 PRIMARY KEY (ICVETRAMITE,ICVEMODALIDAD,ICVEETAPA)
)
;
CREATE TABLE SERVICOM.TRAETAPAXOBJETO
(
   ICVESISTEMA smallint NOT NULL,
   ICVEPROGRAMA smallint NOT NULL,
   COBJETO varchar(15) NOT NULL,
   ICONSECUTIVO smallint NOT NULL,
   IORDEN smallint,
   ICVETRAMITE smallint,
   ICVEMODALIDAD smallint,
   ICVEETAPA smallint,
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070207015517700 PRIMARY KEY (ICVESISTEMA,ICVEPROGRAMA,COBJETO,ICONSECUTIVO)
)
;
CREATE TABLE SERVICOM.TRAGPOREQUISITO
(
   ICVEGRUPO smallint PRIMARY KEY NOT NULL,
   CDSCGRUPO varchar(50),
   CFUNDLEGAL varchar(500)
)
;
CREATE TABLE SERVICOM.TRAGRUPOCONCEPTO
(
   ICVEGRUPO smallint PRIMARY KEY NOT NULL,
   CDSCGRUPO varchar(750),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   LAPLICAFACTORDIRECTO smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.TRAMODALIDAD
(
   ICVEMODALIDAD smallint PRIMARY KEY NOT NULL,
   CDSCMODALIDAD varchar(100),
   LVIGENTE smallint DEFAULT 0 NOT NULL
)
;
CREATE TABLE SERVICOM.TRAOFICIOXSOLICITUD
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVESEGTOENTIDAD bigint NOT NULL,
   CONSTRAINT SQL070207015518570 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD,ICVESEGTOENTIDAD)
)
;
CREATE TABLE SERVICOM.TRAOPNENTTRAMITE
(
   IEJERCICIOSOLICITUD smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVEOPINIONENTIDAD smallint NOT NULL,
   ICVESEGTOENTIDAD bigint NOT NULL,
   COPNDIRIGIDOA varchar(100),
   CPTOOPINION varchar(100),
   CONSTRAINT SQL070207015518890 PRIMARY KEY (IEJERCICIOSOLICITUD,INUMSOLICITUD,ICVEOPINIONENTIDAD,ICVESEGTOENTIDAD)
)
;
CREATE TABLE SERVICOM.TRAPLANOXTRAMITE
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVEPLANO bigint NOT NULL,
   CONSTRAINT SQL070207015519150 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD,ICVEPLANO)
)
;
CREATE TABLE SERVICOM.TRAREFERENCIACONCEPTO
(
   IEJERCICIO smallint NOT NULL,
   ICVECONCEPTO smallint NOT NULL,
   DTINIVIGENCIA date NOT NULL,
   ICATEGORIAINGRESOS smallint,
   ICONCEPTOINGRESOS smallint,
   IREFNUMERICAINGRESOS bigint,
   LESTARIFA smallint DEFAULT 0 NOT NULL,
   LESPORCENTAJE smallint DEFAULT 0 NOT NULL,
   DIMPORTESINAJUSTE decimal(14,4),
   DIMPORTEAJUSTADO decimal(14,4),
   DTFINVIGENCIA date,
   CONSTRAINT SQL070207015519520 PRIMARY KEY (IEJERCICIO,ICVECONCEPTO,DTINIVIGENCIA)
)
;
CREATE TABLE SERVICOM.TRAREGCARACXREQPNC
(
   IEJERCICIO smallint NOT NULL,
   ICONSECUTIVOPNC bigint NOT NULL,
   ICVEPRODUCTO int NOT NULL,
   ICVECAUSAPNC smallint NOT NULL,
   ICVEREQUISITO smallint NOT NULL,
   ICVECARACTERISTICA smallint NOT NULL,
   COBS varchar(200),
   CONSTRAINT SQL070207015519880 PRIMARY KEY (IEJERCICIO,ICONSECUTIVOPNC,ICVEPRODUCTO,ICVECAUSAPNC,ICVEREQUISITO,ICVECARACTERISTICA)
)
;
CREATE TABLE SERVICOM.TRAREGETAPASXMODTRAM
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVEETAPA smallint NOT NULL,
   IORDEN smallint NOT NULL,
   ICVEOFICINA smallint,
   ICVEDEPARTAMENTO smallint,
   ICVEUSUARIO bigint,
   TSREGISTRO timestamp,
   LANEXO smallint DEFAULT 0,
   COBSENVIADACIS varchar(250),
   CONSTRAINT SQL070216090035590 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD,ICVETRAMITE,ICVEMODALIDAD,ICVEETAPA,IORDEN)
)
;
CREATE TABLE SERVICOM.TRAREGPNCETAPA
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVEETAPA smallint NOT NULL,
   IORDEN smallint NOT NULL,
   ICVEPNCXETAPA smallint NOT NULL,
   IEJERCICIOPNC smallint,
   ICONSECUTIVOPNC bigint,
   CONSTRAINT SQL070207015520980 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD,ICVETRAMITE,ICVEMODALIDAD,ICVEETAPA,IORDEN,ICVEPNCXETAPA)
)
;
CREATE TABLE SERVICOM.TRAREGREFPAGO
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICONSECUTIVO smallint NOT NULL,
   IREFNUMERICA bigint,
   INUMUNIDADES smallint,
   CREFALFANUM varchar(15) NOT NULL,
   DIMPORTEPAGAR decimal(12,2),
   DIMPORTEPAGADO decimal(12,2),
   DTPAGO date,
   ICVEBANCO smallint,
   CFORMATOSAT varchar(15),
   LPAGADO smallint DEFAULT 0 NOT NULL,
   ICVECONCEPTO smallint,
   DTMOVIMIENTO date,
   ICVESOLICITANTEINGRESOS bigint,
   CONSTRAINT SQL070207015521760 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD,ICONSECUTIVO)
)
;
CREATE TABLE SERVICOM.TRAREGREQXCAUSA
(
   IEJERCICIO smallint NOT NULL,
   ICONSECUTIVOPNC bigint NOT NULL,
   ICVEPRODUCTO int NOT NULL,
   ICVECAUSAPNC smallint NOT NULL,
   ICVEREQUISITO smallint NOT NULL,
   CONSTRAINT SQL070207015522210 PRIMARY KEY (IEJERCICIO,ICONSECUTIVOPNC,ICVEPRODUCTO,ICVECAUSAPNC,ICVEREQUISITO)
)
;
CREATE TABLE SERVICOM.TRAREGREQXTRAM
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVEREQUISITO smallint NOT NULL,
   IEJERCICIOFORMATO smallint,
   ICVEFORMATOREG bigint,
   DTRECEPCION date,
   ICVEUSURECIBE bigint,
   DTNOTIFICACION date,
   CNUMOFICIO varchar(20),
   DTOFICIO date,
   LVALIDO smallint DEFAULT 0 NOT NULL,
   LTIENEPNC smallint DEFAULT 0 NOT NULL,
   LRECNOTIFICADO smallint,
   CONSTRAINT SQL070216090036710 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD,ICVETRAMITE,ICVEMODALIDAD,ICVEREQUISITO)
)
;
CREATE TABLE SERVICOM.TRAREGSOLICITUD
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   ICVETRAMITE smallint,
   ICVEMODALIDAD smallint,
   ICVESOLICITANTE bigint,
   ICVEREPLEGAL bigint,
   CNOMAUTORIZARECOGER varchar(100),
   ICVEUSUREGISTRA bigint,
   TSREGISTRO timestamp,
   DTLIMITEENTREGADOCS date,
   DTESTIMADAENTREGA date,
   LPAGADO smallint DEFAULT 0 NOT NULL,
   DTENTREGA date,
   ICVEUSUENTREGA bigint,
   LRESOLUCIONPOSITIVA smallint DEFAULT 1 NOT NULL,
   LDATOSPREREGISTRO smallint DEFAULT 0 NOT NULL,
   IIDBIEN bigint,
   ICVEOFICINA smallint,
   ICVEDEPARTAMENTO smallint,
   IEJERCICIOCITA smallint,
   IIDCITA bigint,
   ICVEFORMA smallint,
   LPRINCIPAL smallint DEFAULT 0,
   LIMPRESO smallint DEFAULT 0,
   ICVEDOMICILIOSOLICITANTE smallint,
   ICVEDOMICILIOREPLEGAL smallint,
   CENVIARRESOLUCIONA varchar(150),
   COBSTRAMITE varchar(200),
   ICVEFORMATOREG bigint,
   CDSCBIEN varchar(150),
   DTIMPRESION date,
   ICVEOFICINAENVIARES smallint,
   DUNIDADESCALCULO decimal(10,2) DEFAULT 0,
   LNOTIFICACION smallint,
   LTRAMINERNET smallint,
   CONSTRAINT SQL070216090038550 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD)
)
;
CREATE TABLE SERVICOM.TRAREGTRAMXSOL
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUD bigint NOT NULL,
   DTCANCELACION date,
   ICVEMOTIVOCANCELA smallint,
   ICVEUSUARIO bigint,
   COBS varchar(200),
   CONSTRAINT SQL070216090039050 PRIMARY KEY (IEJERCICIO,INUMSOLICITUD)
)
;
CREATE TABLE SERVICOM.TRAREQEXTRA
(
   ICVEREQUISITO smallint NOT NULL,
   IORDEN smallint NOT NULL,
   CETIQUETA varchar(100),
   CNOMCAMPO varchar(75),
   LACTIVO smallint DEFAULT 0,
   CONSTRAINT SQL101019152601030 PRIMARY KEY (ICVEREQUISITO,IORDEN)
)
;
CREATE TABLE SERVICOM.TRAREQUISITO
(
   ICVEREQUISITO smallint PRIMARY KEY NOT NULL,
   CDSCREQUISITO varchar(700),
   CDSCBREVE varchar(150),
   CFUNDLEGAL varchar(500),
   LVIGENTE smallint DEFAULT 0 NOT NULL,
   LDIGITALIZA smallint DEFAULT 0,
   ICVEFORMATO smallint,
   CMETODOEJECUTA varchar(100)
)
;
CREATE TABLE SERVICOM.TRAREQUISITOXGPO
(
   ICVEGRUPO smallint NOT NULL,
   ICVEREQUISITO smallint NOT NULL,
   IORDEN smallint,
   CONSTRAINT SQL070207015525400 PRIMARY KEY (ICVEGRUPO,ICVEREQUISITO)
)
;
CREATE TABLE SERVICOM.TRAREQXMODTRAMITE
(
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVEREQUISITO smallint NOT NULL,
   IORDEN smallint,
   LREQUERIDO smallint DEFAULT 0,
   CONSTRAINT SQL070207015525690 PRIMARY KEY (ICVETRAMITE,ICVEMODALIDAD,ICVEREQUISITO)
)
;
CREATE TABLE SERVICOM.TRASOLICITUDREL
(
   IEJERCICIO smallint NOT NULL,
   INUMSOLICITUDPRINC bigint NOT NULL,
   INUMSOLICITUDREL bigint NOT NULL,
   CONSTRAINT SQL070207015526190 PRIMARY KEY (IEJERCICIO,INUMSOLICITUDPRINC,INUMSOLICITUDREL)
)
;
CREATE TABLE SERVICOM.TRATIEMPOTRASLADO
(
   ICVETRAMITE smallint NOT NULL,
   ICVEMODALIDAD smallint NOT NULL,
   ICVEOFICINAORIGEN smallint NOT NULL,
   ICVEOFICINADESTINO smallint NOT NULL,
   DTINIVIGENCIA date NOT NULL,
   INUMDIASTRASLADO smallint,
   LDIASNATURALESTRASLADO smallint DEFAULT 0 NOT NULL,
   CONSTRAINT SQL070207015526540 PRIMARY KEY (ICVETRAMITE,ICVEMODALIDAD,ICVEOFICINAORIGEN,ICVEOFICINADESTINO,DTINIVIGENCIA)
)
;
CREATE TABLE SERVICOM.TRATRAMITEXOFIC
(
   ICVEOFICINA smallint NOT NULL,
   ICVETRAMITE smallint NOT NULL,
   ICVEOFICINARESUELVE smallint,
   ICVEDEPTORESUELVE smallint,
   CONSTRAINT SQL070207015526810 PRIMARY KEY (ICVEOFICINA,ICVETRAMITE)
)
;

CREATE TABLE SERVICOM.SEGPERMISOXGPO
(
   ICVESISTEMA smallint NOT NULL,
   ICVEGRUPO smallint NOT NULL,
   ICVEPROGRAMA smallint NOT NULL,
   LEJECUCION smallint DEFAULT 1 NOT NULL,
   LACTUALIZACION smallint DEFAULT 1 NOT NULL,
   CONSTRAINT CC1110497066545 PRIMARY KEY (ICVESISTEMA,ICVEGRUPO,ICVEPROGRAMA)
)
;
CREATE INDEX FKPERMISOXGPO197 ON SERVICOM.SEGPERMISOXGPO
(
  ICVESISTEMA,
  ICVEPROGRAMA
)
;
CREATE INDEX FKPERMISOXGPO194 ON SERVICOM.SEGPERMISOXGPO
(
  ICVESISTEMA,
  ICVEGRUPO
)
;
